### ISSUE TITLE
v3 Text Editor Bug

### ISSUE THREAD

**Issue by rowa97** [stoplightio/desktop#103]
"Nanundefined" displayed when editing text in "editor textboxes."

1. Create a few bullet point list items.
2. Place cursor at the end of one of the lines (not the last one though.)
3. Press "Return"

**Comment by marbemac** [comment]
Will need to dive into SimpleMDE to fix this one.

**Comment by marbemac** [comment]
Dup of #108, which has a more thorough description so consolidating to that one.
