### ISSUE TITLE
Hub page w/included Textblock shows error

### ISSUE THREAD

**Issue by jayshao** [stoplightio/desktop#109]
```
Error: The $ref'd data contains invalid JSON
```

When pointed at a .md file in the same project.

Removing and re-adding the block shows the same error

**Comment by marbemac** [comment]
@casserni this is the issue we talked about this morning - let's get it fixed up today please.

**Comment by casserni** [comment]
Fixed in develop! Now checks file type/language as well as data format when generating error messages.

**Comment by marbemac** [comment]
Deployed and should be all set.
