### ISSUE TITLE
Validations aren't kept anymore in json schema editor (+ trace)

### ISSUE THREAD

**Issue by ntiss** [stoplightio/desktop#110]
Unable to add any validation (or update an existing one).
See this demo : 
![bug_validations](https://user-images.githubusercontent.com/29988779/34358815-2e58c4ce-ea53-11e7-96bb-4248c2323228.gif)

**Comment by marbemac** [comment]
Thanks for the report @ntiss! Fixed and deployed today.

**Comment by ntiss** [comment]
Almost resolved.
Now when updating the validation criteria, the "required" checkbox is unchecked : 

![bug_required](https://user-images.githubusercontent.com/29988779/34379280-bf7cb03a-eafa-11e7-91f1-f00a1a0bef4b.gif)
