### ISSUE TITLE
Adding enum value 0 isn't shown correctly

### ISSUE THREAD

**Issue by wvzuilen** [stoplightio/desktop#111]
Issue found @ https://next.stoplight.io :

I'm trying to add enum values to a integer: 0, 250 and 500. When I fill in 250 the auto-complete shows 'Add 250'. When I press enter, 250 is added to the enum values. When I fill in 0 the auto complete doesn't show 'Add 0'. When I press enter, the 0 value is added to the enum values, but it doesn't show correctly.

<img width="324" alt="schermafbeelding 2018-01-04 om 09 56 05" src="https://user-images.githubusercontent.com/26225750/34556211-be561d72-f135-11e7-94a1-c8e187871978.png">
<img width="441" alt="schermafbeelding 2018-01-04 om 09 56 24" src="https://user-images.githubusercontent.com/26225750/34556218-c2e10e88-f135-11e7-9796-2b5d8aa1cdcb.png">

**Comment by marbemac** [comment]
Ah, should be a simple fix - good catch.

@casserni I bet there is an if condition somewhere that is not accounting for "0" correctly.

**Comment by casserni** [comment]
The issue was that ANY dropdown with an option of value zero, was not displayed because of _.compact, so the other integer validators were also broken. Fixed by changing _.compact to _.without, containing removing all falsey values excluding zero.
