### ISSUE TITLE
Referenced object can't be set required in the Next UI

### ISSUE THREAD

**Issue by wvzuilen** [stoplightio/desktop#114]
Discovered  @ next.stoplight.io

<img width="764" alt="schermafbeelding 2018-01-05 om 11 22 46" src="https://user-images.githubusercontent.com/26225750/34605211-063b8d0e-f20b-11e7-8b5a-71a4559fbd2b.png">

I can't set a referenced object as 'required' in the Next UI. I can set it 'required' in the OAS code. 

<img width="611" alt="schermafbeelding 2018-01-05 om 11 30 17" src="https://user-images.githubusercontent.com/26225750/34605546-55f43336-f20c-11e7-80bb-d3a39d455ded.png">

I would expect a 'Required' checkbox in the UI even when the object is referenced.

**Comment by lottamus** [comment]
@wvzuilen sorry for the late follow up, but this issue has been fixed and released

![image](https://user-images.githubusercontent.com/7423098/37061433-1d4a3630-2159-11e8-9984-43200a60fde0.png)
