### ISSUE TITLE
No example generation when using external referenced objects

### ISSUE THREAD

**Issue by wvzuilen** [stoplightio/desktop#116]
It seems like I can't generate any request/response examples when I'm using a external referenced (reference to a file other then 'this file') object.

<img width="853" alt="schermafbeelding 2018-01-05 om 15 30 19" src="https://user-images.githubusercontent.com/26225750/34613348-bb19762e-f22d-11e7-9f10-4ae4a3237702.png">

**Comment by marbemac** [comment]
This has been fixed, please let us know if you continue to run into it!
