### ISSUE TITLE
Protect hubs from errant null values in spec

### ISSUE THREAD

**Issue by marbemac** [stoplightio/desktop#117]
For example, the hub nameFactory function errors out when children are unexpectedly null.

<img width="379" alt="screen shot 2018-01-05 at 12 31 42 pm" src="https://user-images.githubusercontent.com/847542/34620733-7cc14726-f214-11e7-8dfb-97ae16333bfa.png">

**Comment by marbemac** [comment]
@lottamus since we are not using typescript, I'm not sure we can/should rely on the destructuring pattern we know and love.

```js
const { x, data = {} } = props;

// and

function ({ x, data = {} }) {}
```

Above, data must be undefined to guarantee it gets the default value assigned. Unexpected `null` values come back to bite us. Typescript would allow us to use this pattern more confidently. For now, we probably need to start updating to something like:

```js
const { x } = props;
const data = props.data || {};

function (opts) {
  const { x } = opts;
  const data = opts.data || {};
}
```

Thoughts?

**Comment by lottamus** [comment]
@marbemac agreed.

How did these values get passed in as null? Null usually means it was explicitly set in the code, right?

**Comment by marbemac** [comment]
Yeah I'm not sure - I tried to reproduce via the visual editors but could not.

Note for `x || y` syntax above, we can only use when `x` is never expected to be a number or empty string. `0 || y` and `"" || y` would both clobber `x`. We can use it in most cases though.

**Comment by marbemac** [comment]
Fix deployed earlier this week.
