### ISSUE TITLE
Markdown editor should fill height for easier clicking

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/desktop#118]
When I click in the editor I would expect the cursor to show up.

![weirdcursor.gif](https://codetreeusercontent.s3.amazonaws.com/uploads/895d640e-e8b4-4bf0-b384-6c94f425fb8f/weirdcursor.gif)

**Comment by casserni** [comment]
duplicate of https://codetree.com/projects/WFjL/issues/5605026?assignee=casserni

**Comment by lottamus** [comment]
Duplicate of #122
