### ISSUE TITLE
move off of squirrel for osx desktop upgrade process

### ISSUE THREAD

**Issue by marbemac** [stoplightio/desktop#12]
Problems that hasn't been fixed in a long time: 
https://github.com/Squirrel/Squirrel.Mac/issues/151#issuecomment-195423529

Likely, we need to build a custom / more robust process.

Would be great if:
- prompt the user, show a quick changelog.
- allow the user to opt NOT to upgrade right now.
- built off of github releases <- pull data from here

**Comment by marbemac** [comment]
won't fix for now. we did improve the overall auto updater process in 3.1.0

**Comment by working-name** [comment]
Is there a binary not bundled with this horrible, horrible failure of an auto-updater?
