### ISSUE TITLE
Fixed issue with JSON and can't get rid of message

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/desktop#121]
![fixeditwontgoaway.png](https://codetreeusercontent.s3.amazonaws.com/uploads/3303b658-248d-4312-9f08-cfb40a2af894/fixeditwontgoaway.png)

**Comment by wvzuilen** [comment]
I'm experiencing the same bug. This is also causing I can't save my work normally. Workaround is that I change something in the Info object (at the top of the JSON file), then I can save the file.

**Comment by marbemac** [comment]
Fixed in the deploy this morning, please let us know if it occurs again!
