### ISSUE TITLE
Markdown Editor hiding text at the bottom of the page 

### ISSUE THREAD

**Issue by rowa97** [stoplightio/desktop#122]
![Screen Shot 2018-01-08 at 11.39.47 AM.png](https://codetreeusercontent.s3.amazonaws.com/uploads/81f67162-98c8-4768-b2c7-2148bf1b53e7/Screen+Shot+2018-01-08+at+11.39.47+AM.png)

"Recap" Missing from lefthand Markdown editor

**Comment by pytlesk4** [comment]
Btw, can  you not scroll to the bottom of the window? There are two columns btw.

**Comment by rowa97** [comment]
Can scroll down on the preview side, can't scroll down in the markdown editor
