### ISSUE TITLE
Path parameter ($.ctx) can't be set per scenario step

### ISSUE THREAD

**Issue by wvzuilen** [stoplightio/desktop#127]
Discovered in the Next UI:

I want to make two steps with different path parameter inputs. When I set the $.ctx in step 1 it's also set in step 2. Are these variables shared? How could I test different path parameter inputs?

<img width="385" alt="schermafbeelding 2018-01-10 om 16 34 47" src="https://user-images.githubusercontent.com/26225750/34780924-bfa2800a-f624-11e7-944c-2405c605f451.png">

**Comment by marbemac** [comment]
Hi @wvzuilen, the $.ctx object is primarily used to pass data from earlier steps in a scenario to later steps. For example, the first step might create a new user, and set the random "id" returned from the request to $.ctx.userId. Then, the second step might send a request to something like `GET /users/{$.ctx.userId}` to get the user that was just created.

If you are looking to test specific requests, you do not have to use ctx. For example, you could have step one send a request to `GET /ibans/test1` and step two send one to `GET /ibans/test2` - no $.ctx required. Or you could use two different ctx properties, $.ctx.iban1 and $.ctx.iban2. 

Does that make sense - is there a use case you're after that is not covered here?

**Comment by marbemac** [comment]
Closing this since there are a couple of ways to accomplish the desired outcome - please let us know if you have any more questions about it!
