### ISSUE TITLE
API Docs multipart/form-data request maker not displaying

### ISSUE THREAD

**Issue by lottamus** [stoplightio/desktop#129]
It looks like there is an issue rendering the inputs for multipart/form-data with "Try it out"

![image](https://user-images.githubusercontent.com/7423098/34788025-edca8674-f5fe-11e7-94ea-646378649291.png)

**Comment by celalo** [comment]
I am asking because the issue is closed. Is it resolved? I cannot verify if that's the case.

![kapture 2019-02-12 at 19 47 08](https://user-images.githubusercontent.com/220977/52663658-03fd9780-2eff-11e9-8e5a-d6df41e72bc0.gif)

**Comment by tbarn** [comment]
Hey @celalo, sorry about that. We are only tracking issues with Stoplight Next in this repo now, which is why I closed this issue. Since we opened this one ourselves, I didn't notice you were watching it. We'll watch it internally.
