### ISSUE TITLE
Weird Cursor behvior when toggling preview in the markdown editor for a Scenario Description

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/desktop#130]
![weirdCursor.gif](https://codetreeusercontent.s3.amazonaws.com/uploads/b8fbdd93-52ba-4c5b-bc8f-3206469acd60/weirdCursor.gif)

Kinda hard to see the issue in the gif above, but when I am writing a description and toggle to preview, and I can't move my cursor around with the key pad, and there is weird behavior with the mouse.

**Comment by marbemac** [comment]
Gif is broken.

**Comment by marbemac** [comment]
Following up here, is this still an issue? If so, could you provide a working gif or more specific example?
