### ISSUE TITLE
Can't use properties called "set" in the JSV/JSE

### ISSUE THREAD

**Issue by marbemac** [stoplightio/desktop#132]
For example, try to describe a schema for the JSON example below.

```
{
  "message": "Success",
  "result": {
    "set": [1,2,3]
  }
}
```

**Comment by casserni** [comment]
update all Immutables to static, and then change to immutable.setIn rather than object.setIn

**Comment by casserni** [comment]
https://github.com/stoplightio/core/pull/722

**Comment by casserni** [comment]
https://github.com/stoplightio/core/pull/722
