### ISSUE TITLE
Path Param disappear after any first request

### ISSUE THREAD

**Issue by ntiss** [stoplightio/desktop#138]
After sending a request in the HTTPRequestMaker, the path parameter fields disappear when we try to update the filed value.
There is the same behaviour with query parameters.

![bug_pathparamdisapear](https://user-images.githubusercontent.com/29988779/35146586-cd4d7352-fd0b-11e7-9e41-59d7b93e3e88.gif)

**Comment by casserni** [comment]
PR up for review https://github.com/stoplightio/core/pull/768
