### ISSUE TITLE
XML/HTML failing contract validation regardless of schema

### ISSUE THREAD

**Issue by nextrevision** [stoplightio/desktop#142]
I am currently using Stoplight Next and working with a lot of APIs that render XML. On occasion, the root of these API paths render HTML. I set a schema to basically accept anything, but regardless of the root type is set, I always get this error:

![screen shot 2018-02-08 at 6 24 16 pm](https://user-images.githubusercontent.com/2991219/36003866-d3aa25ae-0cfd-11e8-826b-b50db3cb88fa.png)

I know the example is returning HTML, but I see the same for perfectly valid XML that my actual APIs return.

My schema is set to the following:

![screen shot 2018-02-08 at 6 24 43 pm](https://user-images.githubusercontent.com/2991219/36003898-f1998618-0cfd-11e8-9bf0-619d61407d1b.png)

No matter the change to the schema, creating a complex object, setting anyOf with all the types checked, etc, I always get the `(root): Invalid type. Expected: null, given: string` error.

I know the Open API spec (v2 and v3) support XML schema definitions, but no matter what I change the schema to, I get that error and the test fails.

**Comment by marbemac** [comment]
@pytlesk4 thoughts? This would probably be on the Prism side of things no?

**Comment by pytlesk4** [comment]
@nextrevision This should be fixed now, can you try re running your scenario in the hosted version.

**Comment by nextrevision** [comment]
Yup, this seems to be working now, thanks for fixing it. Excited about the new update!
