### ISSUE TITLE
localhost URL bug in HTTP Request Maker

### ISSUE THREAD

**Issue by tbarn** [stoplightio/desktop#143]
When `http://` is left off for a `localhost`, it pushes the port number to the next text box

![6d042e93b4](https://user-images.githubusercontent.com/2008034/36053975-a24cdf3a-0db9-11e8-9599-a374dc4649ad.jpg)

**Comment by marbemac** [comment]
@casserni is this fixed via the other request maker updates you did?

**Comment by casserni** [comment]
@marbemac should already be fixed in production, seems as though the host selector has been removed for for the modeling request maker

**Comment by marbemac** [comment]
Yup, fixed and merged into develop - will go out on next deploy.
