### ISSUE TITLE
[JSE] Cannot unset an optional format validation once it is set

### ISSUE THREAD

**Issue by tbarn** [stoplightio/desktop#144]
Repro steps:
1. Add a new parameter
2. Set the type to one with validation options, for example, number
3. Set an optional format validation, for example, float
4. Click off of the box
5. Go try to unset the float format validation - unable to unless you go into the Code section

<img width="891" alt="screen shot 2018-02-08 at 1 51 26 am" src="https://user-images.githubusercontent.com/2008034/36055449-0d51920a-0dc2-11e8-9f80-7c470ce4b111.png">

**Comment by marbemac** [comment]
Will go out on next deploy.
