### ISSUE TITLE
[JSE] Selecting new type for property causes weird bug

### ISSUE THREAD

**Issue by tbarn** [stoplightio/desktop#145]
1. Inside of an object, select "array" as a type
<img width="642" alt="screen shot 2018-02-08 at 1 44 42 am" src="https://user-images.githubusercontent.com/2008034/36118566-1a86d582-1003-11e8-85ef-f25dc9ff5ab1.png">

2. Select "string" as the array item type

3. Then, select "number" as another type
<img width="684" alt="screen shot 2018-02-12 at 2 37 57 pm" src="https://user-images.githubusercontent.com/2008034/36118404-86d20686-1002-11e8-8390-b10b2bede4ad.png">

4. Unselect "number" as the type
<img width="681" alt="screen shot 2018-02-12 at 2 38 05 pm" src="https://user-images.githubusercontent.com/2008034/36118413-8c7ce740-1002-11e8-9c68-a2c1216023d2.png">

Expected it to keep it as `array[string]`, not `array[array, number]`

**Comment by marbemac** [comment]
Thanks for the report! Will fix :).

**Comment by marbemac** [comment]
Will go out on next deploy.
