### ISSUE TITLE
Stoplight icon in launcher

### ISSUE THREAD

**Issue by ntiss** [stoplightio/desktop#146]
[Very Minor Issue]
After upgrading Desktop app from 3.5.7 to 3.5.8, the icon in the Ubuntu launcher is the one of Electron instead your nice purple robot : 
![image](https://user-images.githubusercontent.com/29988779/36141791-6586a352-10a6-11e8-8d1e-3f520b013e82.png)

**Comment by marbemac** [comment]
Thanks for the report Nicolas! Was a problem with the open source library we use to help us compile the desktop app - have downgraded the version of that package that we use for now. Fixed in https://github.com/stoplightio/desktop/releases/tag/v3.6.0.
