### ISSUE TITLE
Scenario ID text input doesn't update correctly when switching scenarios

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/desktop#151]
Steps to reproduce

1. Create two Scenarios
2. Delete the ID of one of the Scenarios
3. Navigate to the other Scenario and notice that the ID is gone.

![idTextFieldBug.gif](https://codetreeusercontent.s3.amazonaws.com/uploads/b170e46b-18f9-4e4e-9092-63b86348349d/idTextFieldBug.gif)

**Comment by marbemac** [comment]
Mmm is this a big enough issue to fix? Why would you delete the ID, and then try to navigate away, and then ignore the warning, and then leave it deleted, and then navigate away again?

**Comment by pytlesk4** [comment]
That isn't my normal behavior, just something I noticed.
