### ISSUE TITLE
Combination of allOf and oneOf not represented in UI

### ISSUE THREAD

**Issue by tbarn** [stoplightio/desktop#152]
In V2 and V3, when you do this: 

```
{
  "title": "Test",
  "allOf": [
    {
      "properties": {},
      "oneOf": [
        {
          "type": "object",
          "properties": {},
          "_isOpen": true,
          "children": [
            {
              "type": "string",
              "name": "a"
            }
          ]
        },
        {
          "type": "object",
          "properties": {},
          "_isOpen": true,
          "children": [
            {
              "type": "string",
              "name": "b"
            }
          ]
        }
      ]
    },
    {
      "type": "object",
      "properties": {
        "c": {
          "type": "string"
        }
      }
    }
  ]
}
```
![screenshot 2018-02-23 09 44 18](https://user-images.githubusercontent.com/2008034/36810002-385e824c-1c8f-11e8-95cd-12c0a8c81d62.png)

Only `c` is represented in the schema: 
![screenshot 2018-02-23 09 44 42](https://user-images.githubusercontent.com/2008034/36810057-51c8b928-1c8f-11e8-867d-7262cf1a0d0e.png)

Also, when you generate an example from the schema, it only shows `c` too: 
![screenshot 2018-02-23 09 45 02](https://user-images.githubusercontent.com/2008034/36810091-698289d6-1c8f-11e8-9cd4-c209246f50f0.png)

A helpful user shared one way of potentially displaying it: 
![screenshot 2018-02-27 10 06 27](https://user-images.githubusercontent.com/2008034/36810304-e6b2797a-1c8f-11e8-90f1-26eceade6374.png)

**Comment by tatiana-perry** [comment]
I'd like to bump this. We have a spec file that uses this and its a blocker for public release right now.

**Comment by tbarn** [comment]
@tatiana-perry we have done some work to improve this in the current sprint. It isn't totally fixed, but it is working better for most use cases. Can you give me an example model to test out to see if it is working for you?

**Comment by tatiana-perry** [comment]
Here is a link to the spec file in Stoplight: 
https://next.stoplight.io/bigcommerce/api-documentation/version%2F1.0/Promotions.oas3.yml

You can really see it under the Condition Model compared to if you paste the same spec file into editor.swagger.io and view the Condition there.

**Comment by tbarn** [comment]
This is in OAS 3, not OAS 2, right? Looks like it is working nicely in your OAS 2 document.

**Comment by tatiana-perry** [comment]
It's not really working in OAS 2 either. If you have more than one ref in oneOf it will render the first one only. 
You can see we have a lot of oneOf's especially under Condition or Rule.

**Comment by tbarn** [comment]
Okay, I see your models are a bit different now in OAS 2 and OAS 3 for Condition. If you could share the raw schema here for what you want, that would be super helpful and I'll test it out with what we have fixed, but haven't released yet.

**Comment by tbarn** [comment]
Or I can assume what you have OAS 3 is what you want. Just let me know!

**Comment by tatiana-perry** [comment]
3.0 is what I want. The 2.0 is my attempt to move things around and make them render. So I'm just testing different setups right now.

**Comment by tbarn** [comment]
Hey @tatiana-perry, can you test this out in your OAS2 specification in the web app? We released some updates to this area of the application and it looks like it might be fixed now, but I wanted to double check with you.

**Comment by tatiana-perry** [comment]
Looks like its fixed. Thanks
