### ISSUE TITLE
UI bug in Mocker to test request

### ISSUE THREAD

**Issue by ntiss** [stoplightio/desktop#154]
The target hostname disappears as soon as I type any char in the path input text :

![bug_prism_mocker](https://user-images.githubusercontent.com/29988779/36978476-da9d554e-2084-11e8-88b8-8c67532b213c.gif)

This bug only happens with the online version inside a browser. It works fine with the desktop app.

**Comment by casserni** [comment]
@ntiss Should've be fixed with the deploy last night!
