### ISSUE TITLE
Cannot unselect a license

### ISSUE THREAD

**Issue by tbarn** [stoplightio/desktop#156]
In v3, you cannot unselect a License once you have picked one in the UI

Going into the Code section is the only way to remove it.

**Comment by alangibson** [comment]
It would be nice if that field would also allow free text entry in additional to allowing unselection. Adding something not in the dropdown via Code results in a green checkmark for License, but nothing in the dropdown box.

**Comment by jayshao** [comment]
Being able to label a proprietary license would be most useful.

**Comment by casserni** [comment]
Removal and the addition of custom Licenses will be added with the next deploy!
