### ISSUE TITLE
Interface Hangs

### ISSUE THREAD

**Issue by jalleyne** [stoplightio/desktop#158]
in v3.7.1 OSX Desktop, the app window becomes unresponsive after running a scenario. The mouse cursor freezes as a hand over the window and it takes no keyboard or mouse input but the top navigation works. 

I had to quit the app or reload the window a few times already, but while writing this bug the window became responsive again and randomly showed the check for updates window. looks like it might be a hung update check that was causing resource strain.

**Comment by tbarn** [comment]
Hey @jalleyne! Have you tried downloading the latest version here: https://github.com/stoplightio/desktop/releases

We fixed an issue with the feature that let you update from the app, which might be causing the issue.

**Comment by jalleyne** [comment]
hey taylor, yes this all started happening after i upgraded to the latest
version 3.7.1 from version from 3.6.x

**Comment by tbarn** [comment]
@jalleyne does it also happen in latest 3.7.2 release too?

**Comment by jalleyne** [comment]
No i havent been able to reproduce it, even before upgrading from 3.7.1 to 3.7.2. From the behavior i noticed, i'm inclined to think that it was something hanging in reconciling a version check or some routine that runs after upgrade. Primarily because i upgraded and then the hanging started, then stopped when the update window randomly popped up saying i was up to date.
