### ISSUE TITLE
Enhancement: Human-friendly deep links

### ISSUE THREAD

**Issue by alangibson** [stoplightio/desktop#160]
Deep links to operations are urlencoded by the browser, resulting in links that look like:

`https://next.stoplight.io/org/project/blob/master/main.oas2.yml?edit=%23%2Fpaths%2F~1api~1v1~1browse%2Fget`

It would be nice to use some sort of human-friendly slug so that people can easily read what you pasted in Slack, etc.

**Comment by lottamus** [comment]
Queries in [v4.0.0](https://github.com/stoplightio/desktop/releases/tag/v4.0.0) will no longer escape slashes

Ex: https://next.stoplight.io/org/project/blob/master/main.oas2.yml?edit=/paths/~1todos/get
