### ISSUE TITLE
Ref Builder resets reffed scenarios in Prism Instances

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/desktop#161]
Attached is a gif illustrating the issue.

Here is a prism instance that illustrates the issue: https://next.stoplight.io/stoplight/prism/blob/master/todos.mocker.cors.prism.yml

To reproduce, just navigate around, and wait for the save button to update to purple.

![refbuilderresetsrefs](https://user-images.githubusercontent.com/2294309/37684062-af6d16be-2c5c-11e8-9c7a-47875e8ce131.gif)

**Comment by lottamus** [comment]
This has been fixed in [v4.0.0](https://github.com/stoplightio/desktop/releases/tag/v4.0.0)
