### ISSUE TITLE
Provide actual curl requests generated by scenario in UI

### ISSUE THREAD

**Issue by johnmckinzie** [stoplightio/desktop#163]
It would be nice if you could expose the actually curl requests that were generated by the scenario framework. This could be helpful for sharing outside of the tool.

**Comment by lottamus** [comment]
You can view the generated code for several languages including curl by clicking the "Code Generation" tab.

This tab will also get updated with the correct `$.ctx` variables after running the Scenario.

![image](https://user-images.githubusercontent.com/7423098/37998965-6bde483e-31e6-11e8-8e22-1d7a7bee19c4.png)
