### ISSUE TITLE
Enhancement: Sort Project List

### ISSUE THREAD

**Issue by MCalder-j2** [stoplightio/desktop#167]
The project list for my org is not sorted in any discernible fashion, making it a bit of a pain to have to scan through the list to find the project I want to work on.

Could you please (at a minimum) sort the project list alphabetically?

If you could provide sort options on the interface, perhaps by name or by last activity timestamp, that would be nice too, but by default it should be alphabetically sorted.

**Comment by lottamus** [comment]
It looks like the project list is currently being sorted by "path" thus if your path does not resemble your name then this will appear off.

Super simple the change the initial sort to be based off of name. We are planning on beefing up the sorting/filtering/searching in the same release as pagination.

**Comment by marbemac** [comment]
@lottamus notice that sorting is currently case sensitive, so uppercase names will be sorted, followed by lower case names sorted. Probably not what we want?
