### ISSUE TITLE
Scenario cURL Code Generation incorrect

### ISSUE THREAD

**Issue by johnmckinzie** [stoplightio/desktop#169]
It appears the cURL code generation has a few bugs. As you can see from below, `http` is being prepended to the URL. Also, the body is being sent as a string and not a JSON object.

```
curl --request POST \
  --url http://https//<domain removed> \
  --header 'content-type: application/json' \
  --data '"{\n  \"code\": \"{$$.env.2FAcode}\",\n  \"email\": \"{$.ctx.email}\"\n}"'
```

**Comment by tbarn** [comment]
@johnmckinzie is this from app.stoplight.io or next.stoplight.io?

**Comment by johnmckinzie** [comment]
That's from https://next.stoplight.io/.

**Comment by tbarn** [comment]
@johnmckinzie could you check your env host name? We think there might have been a typo in it because it says `http//` with a missing `:`. Our code generation checks for `http://` and `https://`.

**Comment by casserni** [comment]
@johnmckinzie I found the issue and it seems to be appending to the url regardless, thanks for pointing this out! I'll get on this right away.

**Comment by casserni** [comment]
Will be included in the next deploy!

**Comment by marbemac** [comment]
Live!
