### ISSUE TITLE
Support intra page anchors in hub markdown in app

### ISSUE THREAD

**Issue by marbemac** [stoplightio/desktop#170]
Published hubs work fine, but looks like anchors are getting stripped in the URLs in the hub viewer when in app.

Click on the "This link" link in the content on this page to see it scroll and work in a published hub: https://highmark-scratch.tech-docs.io/api-reference/intro.

```md
# Introduction

Here is the content yada yada...

[This link](#foo-bar) will scroll to the foo bar section.

[This link](/another-page#foo-bar) will scroll to the foo bar section after routing to /another-page.

Lots more content to make enough space should be here...

# Foo bar

Here is the section.
```

**Comment by casserni** [comment]
Added custom scroll logic for react-dom-router NavLink

**Comment by marbemac** [comment]
Live!
