### ISSUE TITLE
Unable to Design/Run/etc the scenarios in browser

### ISSUE THREAD

**Issue by ntiss** [stoplightio/desktop#171]
Hello,

It's not possible anymore to access the design UI of scenarios.
Only the code is displayed with no possibility to move on Design. The Menu bar on top is empty, there are few traces in console : 

![image](https://user-images.githubusercontent.com/29988779/38242620-87aee998-3735-11e8-84a5-807f80aabc81.png)

Bug using Chrome 65.0.3325.181(64 bits) and Firefox Quantum 59.0.1 (64 bits)

(It works fine in the desktop app 4.0.1)

**Comment by ntiss** [comment]
Seems fixed today. Can you confirm ?

**Comment by marbemac** [comment]
Confirmed fixed.
