### ISSUE TITLE
Unable to connect with (old) Firefox

### ISSUE THREAD

**Issue by ntiss** [stoplightio/desktop#172]
It's not possible anymore to log in NextStoplight through Firefox 45.2 ESR.
After filling username and password, the screen just refreshes and stays on login screen.
Here is the trace in console : 

![login_bug_stoplight](https://user-images.githubusercontent.com/29988779/38242869-2fb74554-3736-11e8-95f2-b9b155336ae4.PNG)

It works on recent version of Firefox but these users work on Enterprise computers : they can't upgrade Firefox at all. (admin required, enterprise policy).

**Comment by marbemac** [comment]
Hi Nicolas, we've started to remove some of the polyfills for very old browsers because they result in noticeably slower runtime code for all users. That said, we'll doing some testing today to make sure FF >= 45 works, and will let you know when its live.

**Comment by ntiss** [comment]
Hi Marc,
Thanks for the feedback.

**Comment by marbemac** [comment]
This is fixed - we've updated our browser support targets to be >= Firefox 45, Chrome 50, and Microsoft Edge 14. The update will be deployed tomorrow.

**Comment by marbemac** [comment]
Live!

**Comment by ntiss** [comment]
Successfully tested.
Thanks.
