### ISSUE TITLE
Error when building documentation

### ISSUE THREAD

**Issue by ehosanski** [stoplightio/desktop#174]
For some unknown reason, I keep having an error when building my documentation. There is no explicit error message so I don't know why...

<img width="708" alt="capture d ecran 2018-04-04 a 17 31 44" src="https://user-images.githubusercontent.com/25955608/38317949-870e3bfc-382e-11e8-8b28-ff238a73f468.png">

**Comment by tbarn** [comment]
Hey! Could you send in an email into support@stoplight.io with the project this is happening in? We want to dig a bit deeper into it.

**Comment by lottamus** [comment]
We have identified and fixed an issue causing some larger builds to error. This fix will go out in the next release.
