### ISSUE TITLE
UNUSED_DEFINITION warning on all models

### ISSUE THREAD

**Issue by josecoelho93** [stoplightio/desktop#177]
All the models in my spec are reporting a UNUSED_DEFINITION warning even though I am using them as shown in the image.

![imagem](https://user-images.githubusercontent.com/38102089/38362823-1e048ca0-38ca-11e8-8c52-3736367e1eef.png)

**Comment by casserni** [comment]
Fix will be in next deploy!

**Comment by marbemac** [comment]
Live!
