### ISSUE TITLE
Complete button won't close modal

### ISSUE THREAD

**Issue by josecoelho93** [stoplightio/desktop#178]
When I click the Complete button nothing happens

![imagem](https://user-images.githubusercontent.com/38102089/38362908-6eb265aa-38ca-11e8-9fa7-5bcaf42caedf.png)

**Comment by marbemac** [comment]
This is indeed confusing, since it looks like a button (it is not). Will fix!

**Comment by josecoelho93** [comment]
@marbemac  then there is another problem, for this specific endpoint (PUT) I cannot set the request body to a $ref, even though it shows "Complete"

After I select the $ref definition and click away to close the modal I just get this
![imagem](https://user-images.githubusercontent.com/38102089/38377825-e123bc64-38f3-11e8-8961-996c201c19f2.png)

**Comment by marbemac** [comment]
Can you shoot the browser URL to this endpoint in stoplight to support@stoplight.io when you get a chance?

**Comment by josecoelho93** [comment]
@marbemac  Done!

**Comment by casserni** [comment]
@josecoelho93 Both issues have been fixed and will be included with the next deploy. Thanks again for pointing them out to us!

**Comment by marbemac** [comment]
Live!
