### ISSUE TITLE
Difficult to edit security schemes

### ISSUE THREAD

**Issue by josecoelho93** [stoplightio/desktop#179]
When defining OAuth2 security scheme I can only choose accessCode as OAuth2 flow.

![imagem](https://user-images.githubusercontent.com/38102089/38363241-d39f4158-38cb-11e8-9541-90663bb98b07.png)

Authorization and Token URL are troublesome to edit. If I import a specification I cannot edit theses URLs

**Comment by josecoelho93** [comment]
Sure can but I'm just testing the app, I can wait for the bug fix. Thanks.

**Comment by casserni** [comment]
Thanks for pointing this out! The other flow types have been added and will be included in the next deploy!

**Comment by marbemac** [comment]
Live!
