### ISSUE TITLE
Linux version of desktop locks up

### ISSUE THREAD

**Issue by mmontanez-c7ks7s** [stoplightio/desktop#180]
Whenever I click on "Tests" in the tests scenarios, the tab never becomes visible, and the entire application locks up.  The pointer changes to the "hand" (as it does when you mouse over a link), and never changes back.  I have to quit the application in order to get control back.  Sometimes, if I don't quit immediately, it gets to the point where my entire computer is locked up and I have to do a hard reboot.

It also seems to lock if I run a request which doesn't connect.

This really makes the product unusable for me, as I use Linux only on my workstation.  I'm using Ubuntu 17.10 (latest release).

**Comment by marbemac** [comment]
Hi @mmontanez-c7ks7s could you email the browser URL to your specification (or whichever file seems to lockup) to support@stoplight.io when you have a chance? Depending on the complexity of the spec, this might be related to #176.

**Comment by tbarn** [comment]
@mmontanez-c7ks7s just got your specification. does similar behavior happen when you use the web application? also, do you see it slow down in other areas of the app? thanks!

**Comment by mmontanez-c7ks7s** [comment]
Hi Taylor,


No, the "Tests" tab is the only area where I've seen the behavior consistently.  I haven't used the rest of it as much though.  I will say that after using the app for a while, the overall performance seems to degrade markedly.  I noticed that behavior on Windows as well./


I haven't been able to get the spec to load on the web app.  It always fails with "Importer error".


Melissa


________________________________

**Comment by marbemac** [comment]
We have moved the spec resolution process into a web worker, which means it won't block the UI rendering process anymore. There are a couple of other hotspots that block the UI rendering that we will eventually move into the worker, but the resolution process is the big one. We'll be releasing an update to the desktop app soon that includes this fix, in the meantime give it a go in the web app and let us know how it works out.

**Comment by mmontanez-c7ks7s** [comment]
Hi, I tried with the web app (next.stoplight.io) and I still seem to have the same issue with the Tests tab.

________________________________

**Comment by marbemac** [comment]
I spoke too soon - this is a different issue than the resolving performance issue. We're looking into this one now!

**Comment by marbemac** [comment]
Alrighty we've pushed a fix - please let us know how it works out for ya!

**Comment by mmontanez-c7ks7s** [comment]
Looks like it's working now.  Thank you!

________________________________
