### ISSUE TITLE
Not all people are displayed : further informations

### ISSUE THREAD

**Issue by ntiss** [stoplightio/desktop#183]
Please find here some additional informations about issue #165 : 
I hope that it will help you to fix all the impacts of the issue.

* The temporary bump to 100 users only retrieves 50 people maxi. Even if the request has "?page=1&per_page=**100**"

* It's not possible to add people in a team if they are after the 50 first people of the org. In fact, the "invite area" looks in the resultset previously loaded, and not in the DB when I type a new char in the input field.
![image](https://user-images.githubusercontent.com/29988779/38643548-c855970e-3ddd-11e8-8981-dcb67e4be7dc.png)

* Same problem (same cause) if I want to give write access to a user in a specific project : 
![image](https://user-images.githubusercontent.com/29988779/38643696-552970ce-3dde-11e8-90c8-8e320148c706.png)

**Comment by marbemac** [comment]
@rainum could you make sure per page limit is going up to 100 for member / access list API operations?

**Comment by rainum** [comment]
@marbemac this pull should fix the issue https://github.com/stoplightio/platform/pull/1018
