### ISSUE TITLE
Guests do not see any content upon selecting a project

### ISSUE THREAD

**Issue by MCalder-j2** [stoplightio/desktop#184]
We have a small number of Members (people who create and update specs and content) in our organization, and a large number of Guests (read-only).  Since the last major upgrade, none of our Guests are able to see anything when they select a project.  Changing their role from Guest to Member fixes this, but this is not a solution.  At some point, you are going to lock the organization back down so that I can only have a limited number of Members and then I'm going to be in a real pickle.

**Comment by ntiss** [comment]
Hi @MCalder-j2 
Take a look here and particularly the last comment : #168  (work in progress).

**Comment by MCalder-j2** [comment]
My apologies.  I actually did look through the issues to make sure I wasn't creating something redundant, but I guess I missed seeing #168.  So yes, this is a replication of that one.

**Comment by marbemac** [comment]
Closing this to consolidate to #168 - we're hope to have a proper fix for this out this week.
