### ISSUE TITLE
Add a way to block http redirects

### ISSUE THREAD

**Issue by distinctgrey** [stoplightio/desktop#189]
It seems like Stoplight 4.0 automatically follows redirects.
This makes it impossible to test e.g. a 302 response with Location header.

In Postman, there's a "Automatically follow redirects" toggle.
Could this also be introduced in Stoplight? Preferably with both a global setting with local override.

Thanks!

**Comment by pytlesk4** [comment]
Great question, and if you go to the code editor in Scenarios and add the snippet below:
{
...
  "settings": {
     "http": {
       "redirects": 0
     }
  },
...
}


![disableredirects](https://user-images.githubusercontent.com/2294309/38937650-47d90bb8-42e9-11e8-9187-387fcc0b0234.gif)

**Comment by distinctgrey** [comment]
Works like a charm, thanks!

Any plans to:
- make this setting available per scenario step (instead of only on complete scenario)
- integrate Prism settings into the UI
?

**Comment by pytlesk4** [comment]
Yes and yes, it is on our roadmap, should be getting to it sooner rather than later.
