### ISSUE TITLE
Basic Auth header is not added in hosted docs

### ISSUE THREAD

**Issue by distinctgrey** [stoplightio/desktop#190]
In the OAS file, I've defined a "basic" type security scheme, and attached it to an endpoint.

When testing this endpoint in a scenario, the Basic Auth header is correctly added (and username/password variables are filled in):

<img width="500" alt="stoplight_01" src="https://user-images.githubusercontent.com/1928790/38932098-86087b7c-4315-11e8-8faa-ecb40cc39af6.png">

But after linking the OAS file to a hubs page and publishing the docs, the env variables are not filled i.
And after manually entering them, they are not converted to a Basic Auth header when running the request:

<img width="500" alt="stoplight_02" src="https://user-images.githubusercontent.com/1928790/38932178-bd30ac14-4315-11e8-9333-5d3dc268091e.png">

I'm pretty sure this is a bug?
Unfortunately, this blocks us from testing any request in the hosted docs (since the header is not added, every endpoint returns a 401).

**Comment by marbemac** [comment]
Thanks for the detailed report! Very helpful, and we have deployed a fix :). Let us know how it works out for ya.
