### ISSUE TITLE
Cannot remove Auth0 from publishing

### ISSUE THREAD

**Issue by tbarn** [stoplightio/desktop#198]
If you enter Auth0 setup info, there's no way to remove it

Tried to remove it from the text input boxes and rebuild, but it is still there after rebuilding docs

**Comment by tbarn** [comment]
The last text box is auto-generated, the other two before that are entered by the end user.

**Comment by tbarn** [comment]
Is this for Auth0 or for the basic username/password option?

**Comment by rlauriston** [comment]
Basic. Might not be the same issue.

**Comment by lottamus** [comment]
This issue has been fixed
