### ISSUE TITLE
v3 portals (docs) umbrella

### ISSUE THREAD

**Issue by marbemac** [stoplightio/desktop#21]
Placeholder issue for our next generation documentation platform.

Spoiler - it will generate static HTML, interop with Swagger, have a plugin system, and be open source :).

**Comment by Loiiii** [comment]
Ok

**Comment by jayshao** [comment]
Gitbook style content blocks to be able to put in PlantUML, or other content into Markdown or as content blocks would be *amazing*

Actually - I would love an include syntax inside Markdown for other content like API includes or JSON examples... right now I end up bookending dynamic content with 2 Markdown blocks -but that won't fit into my future idealized github PR workflow... ;)

**Comment by marbemac** [comment]
Closing this as we are tracking in several other cards, and are approaching release. PlantUML should be possible later this year as we transition towards making the entire system more extensible :).
