### ISSUE TITLE
Prism Instance methods should be an array of strings

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/desktop#211]
![methodsinvalidformat](https://user-images.githubusercontent.com/2294309/40008174-51d54cc8-5764-11e8-9140-1ce681d4217e.gif)

methods should be an array of strings like so:

```
'methods': [
  'get',
  'post',
  'put'
]
```

**Comment by casserni** [comment]
Will go out with the next deploy

**Comment by marbemac** [comment]
Fixed in v4.2.0
