### ISSUE TITLE
Tags are sorted strangely

### ISSUE THREAD

**Issue by drieselliott** [stoplightio/desktop#214]
Currently when I add tags to my API endpoints they seem to be sorted in a strange order in 'read' mode. Would it be possible to sort them alphabetically or to make the sort order configurable?

**Comment by casserni** [comment]
@drieselliott Thanks for pointing this out! Updated so that main groupings (tagged operations) will show up alphabetically in read-view, with "Reference" (untagged operations) and "Models" sections always showing at the bottom. Will go out with the next deploy.

**Comment by lottamus** [comment]
Update on this:

Tags will be sorted in the same order they are in the OAS spec. If you want to change the ordering, you will need to go into the "code view" and rearrange the tags.

Any paths that aren't tagged will be sorted alphabetically and put in the "Reference" section below the last tag and above the "Models" section.
