### ISSUE TITLE
AWS auth signing fails when query parameters are set on request

### ISSUE THREAD

**Issue by rossmcdonald** [stoplightio/desktop#217]
Requests that contain query parameters seem to fail the AWS signature check. Removing the query parameters and re-running the request (with the same headers) results in a successful request, so I believe the query params are simply not taken into account when generating the signatures.

The error returned:

```json
{
  "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."
}
```

**Comment by pytlesk4** [comment]
Does this happen when you generate the headers? Or when prism generates them?

**Comment by rossmcdonald** [comment]
This happens when clicking "Update Request" in the UI, so client-side.

**Comment by casserni** [comment]
@rossmcdonald I am not able to replicate, can you try again and let me know if this is still an issue?

**Comment by rossmcdonald** [comment]
@casserni Where did you try? I'm still seeing this in production. To reproduce I:

* Add AWS auth credentials, update request with header, send request

  ![screenshot_2018-08-01 aws-test scenarios yml aws-test stoplight 1](https://user-images.githubusercontent.com/4060903/43548313-3af87444-95a3-11e8-92a7-d5b0616ef1cf.png)

* Remove auth header (just to be safe, keep everything else the same), add a query parameter (`?foo=bar`), update request with auth header, send request

  ![screenshot_2018-08-01 aws-test scenarios yml aws-test stoplight 2](https://user-images.githubusercontent.com/4060903/43548325-43a92994-95a3-11e8-8583-1b745f17350c.png)

**Comment by pytlesk4** [comment]
@rossmcdonald, just want to make sure this isn't a prism issue, if you add the query string param, and remove the auth header, and send the request, the response is a 200?

**Comment by rossmcdonald** [comment]
@pytlesk4 No, I get a 403:

```
{
  "message": "Missing Authentication Token"
}
``` 

II'm fairly certain this is all client-side, but I could be wrong.
