### ISSUE TITLE
Improved Prism debug output

### ISSUE THREAD

**Issue by drieselliott** [stoplightio/desktop#224]
I'm currently getting a lot of `Please set up prism instance.` error messages, while I'm using the hosted version of Prism. When updating my rules after a while my mock seems to work again.

Some improvements to the Prism output could be:
* Indicate if an URL matches no rules
* If a javascript error occurs when executing a script, indicate this to the user

**Comment by tbarn** [comment]
We've recently add this mocking FAQ: https://docs.stoplight.io/mocking/faq

Also, it will soon be added to response in the error cases where we don't have a helpful, specific error message. We usually see if a few different reasons why it fails, which are now covered in the FAQ. 

We're also working on a newer version of Prism, which should hopefully have helpful error messages.
