### ISSUE TITLE
`output` and `$$.response` are empty in after script

### ISSUE THREAD

**Issue by svallory** [stoplightio/desktop#225]
That's pretty much it. The response is showing alright in the "Body" tab though. Here's a screenshot

![image](https://user-images.githubusercontent.com/117560/40641007-9aaf3f4a-62ee-11e8-8bd5-6badea5a117e.png)

**Comment by pytlesk4** [comment]
@svallory thanks for creating an issue, and you are really really close, just update your after script to...

```js
console.log("OUT:", output.get());
console.log("RESPONSE:", $$.response.get());
```

Here are the prism runtime [docs](https://docs.stoplight.io/mocking/javascript-runtime)

Have fun!
