### ISSUE TITLE
Users with read only access cannot run Scenarios 

### ISSUE THREAD

**Issue by tbarn** [stoplightio/desktop#228]
<img width="1280" alt="screen shot 2018-05-31 at 11 22 50 am" src="https://user-images.githubusercontent.com/2008034/40794572-36fe4b0c-64c5-11e8-9ec6-2beb53d8008f.png">

Screenshot from a user with read only access to project in an organization

Top bar that includes the run button is missing

**Comment by marbemac** [comment]
Fixed in v4.2.0
