### ISSUE TITLE
RouteData error when Base Path is specified

### ISSUE THREAD

**Issue by rlauriston** [stoplightio/desktop#229]
![app-mgmt](https://user-images.githubusercontent.com/34748959/40797431-ef7fc57e-64bc-11e8-893d-6b21c997d15b.gif)

The developer thinks that looks like this bug:

https://github.com/nozzle/react-static/issues/567

**Comment by rlauriston** [comment]
1. Right, `/webui/onlinedocs/apis/app-mgmt` is the base path I set in **Publish > Advanced > Base Path**.
2. I don't know. How would we test that?
3. Done.
4. Striim is a server platform that's installed on customers' premises or in private VMs in AWS / Azure / whatever. I'll ask the developer to post exact details of what web server they're using.

**Comment by marbemac** [comment]
Great thanks. Re 2, we'll do some initial testing for you using the built docs you sent over. Will followup with more questions if needed.

**Comment by marcinStriim** [comment]
Hello
We use Jetty to host it.

**Comment by lottamus** [comment]
You don't need to load the route with `/index.html` in the pathname. We are using React so once the JavaScript loads it will fetch a JSON file keyed by the pathname which contains data to render the page. If that file fails it should display a 404 page, but it looks like its just displaying a blank screen in this case.

Can you try loading just `/webui/onlinedocs/apis/app-mgmt/`? This is working on my end.

![image](https://user-images.githubusercontent.com/7423098/40927793-439312b2-67e5-11e8-87b5-16822e635cd1.png)


I will create a new issue for the blank 404 page

**Comment by marcinStriim** [comment]
Hi @lottamus 
It worked!
It looks like the problem was easier than I expected.

Thanks a lot for your help.

**Comment by rlauriston** [comment]
Thanks for the quick assistance, we're shipping tonight.
Maybe redirect <base path>/index.html to <base path>?

**Comment by rowa97** [comment]
The documentation for Embedding your Hub is live!  https://docs.stoplight.io/documentation/Embed-your-Hub

**Comment by lottamus** [comment]
Closing this in favor of #233
