### ISSUE TITLE
Changing security definition object keys is not intuitive

### ISSUE THREAD

**Issue by ChrisNLott** [stoplightio/desktop#24]
By default new security definitions start with the key ```new_auth```. In order to change this, you need to know to click on the ```securityDefinitions``` path and change it in JSON.

Perhaps we can add some UI tooling to make this more apparent. For example allowing you to click on ```securityDefinitions``` and showing some form inputs.

![change-security-name](https://cloud.githubusercontent.com/assets/7423098/24470649/4d492ef4-1485-11e7-92f8-dc6c73341bee.gif)

**Comment by marbemac** [comment]
will be included in todays deploy
