### ISSUE TITLE
Allow users with read access to select an environment

### ISSUE THREAD

**Issue by tbarn** [stoplightio/desktop#240]
> As Admin or Write Access user, I can see the “Environments” button in the upper right corner, enabling me to switch between environments.
> 
> Environment variables (e.g. user credentials for basic auth) are also automatically filled in when using Read view.
> 
> This provides a really quick way to use the “Send a Test Request” feature.
> 
> I think it’s kind of weird that Read Access users have no possibility to select an environment.
> Since the people consulting the API spec (e.g. for clientside development) are imo the primary target users of the “Send a Test Request” feature, they’d benefit most from auto-filling variables.

from: https://community.stoplight.io/t/shouldnt-a-read-access-user-be-able-to-switch-between-environments/136

**Comment by lottamus** [comment]
When in readonly mode, the toolbar is only visible for the Scenarios editor.

We can change this to show for all editors

**Comment by tbarn** [comment]
Fixed in v4.3.0

**Comment by distinctgrey** [comment]
Thanks for the fix guys! Much appreciated!
