### ISSUE TITLE
Collapsable Page Titles in Subpages

### ISSUE THREAD

**Issue by tbarn** [stoplightio/desktop#242]
This fix would help other users with lots of APIs on one API Reference page. 

> If I am adding services and sub pages it would be nice to have the page names be top level and click to expand the Resources and Models. My API will have 20+ services and to have Resources and Models in each displayed by default and no way to collapse into main page title will make my table of contents list very very long.

![](https://community.stoplight.io/uploads/default/optimized/1X/072b42d1dfba36970727948ee719db1dfe1739a2_1_580x500.png)

From: https://community.stoplight.io/t/collapsable-page-titles-in-sub-pages/123

**Comment by lottamus** [comment]
This can be achieved now by nesting the API references one more level deep.

For example, create a subpage called "Services" and add subpages underneath that for each service

![image](https://user-images.githubusercontent.com/7423098/41927182-1cf04914-7937-11e8-977a-bea386ceb104.png)

**Comment by tbarn** [comment]
Please post to: https://community.stoplight.io/t/collapsable-page-titles-in-sub-pages/123
