### ISSUE TITLE
Guide to HTTP Request

### ISSUE THREAD

**Issue by ozum** [stoplightio/desktop#247]
Hi,

**I read docs** but cannot successfully send request to endpoints (except ToDo examples) using Stoplight Next Desktop. I was using v2 without problem.

Steps currently I follow in Stoplight Next Desktop:
1. Create a new project
1. Delete sample ToDo models and endpoints (requests for them are working somehow)
1. Create some models and endpoints using CRUD builder. (Called `organization`)
1. Install `prism`
1. execute `prism mock --spec "https://exporter.stoplight.io/[I PUT PROJECT ID HERE]/master/mocker.prism.yml"`
1. In Stoplight Next Desktop click `HTTP` and send a request to `http://localhost:4010/organizations`
1. Got response 400: `{
  "error": "Mocking is enabled, but there is no operation defined for GET /organizations in the connected specification files."
}`

My questions are:
1. During api design, do I need to install and run `prism` to send request in `Read` and `HTTP` parts of the Stoplight Next Desktop. (In desktop v2 it was possible without installing `prism`)?
1. Could you please explain step by step how to make a simple request for mocked data in Stoplight Next Desktop?

Kind Regards,

**Comment by tbarn** [comment]
Hey @ozum! 

We took a look at it and it appears to be having some strange behavior. We've recreated your issue with your specification and are still trying to figure out what is going on. You are doing it exactly how you should be doing a simple request.

**Comment by ozum** [comment]
@tbarn thanks, I'm waiting for a possible solution, because I'm stuck.

**Comment by pytlesk4** [comment]
Thanks for the detailed report @ozum, got a fix for you that will be going out later today. Will be live in the hosted and binary version of prism shortly.

**Comment by redplane** [comment]
I'm haing same issue with `next.stoplight.io` on web.
I use web prism that provided by stoplight, but failed.

**Comment by tbarn** [comment]
@redplane can you give more details of what your setup is like? This error can appear for different problems so it might be something different.
