### ISSUE TITLE
Headers in API Spec path responses do not pull in shared parameters

### ISSUE THREAD

**Issue by onedotover** [stoplightio/desktop#25]
Version 3.2.0

When adding a header to a path response, it provides options for linking to a shared parameter, documentation, settings, required, and delete. Linking to a shared parameter does not load the list of parameters.

**Comment by marbemac** [comment]
Hmm interesting, thanks for the report! Will have somebody look into it asap.

**Comment by marbemac** [comment]
Ok so turns out $refs in response headers are not supported. We've gone ahead and removed the option from the UI to avoid confusion. All set!
