### ISSUE TITLE
x-chance in v4

### ISSUE THREAD

**Issue by ozum** [stoplightio/desktop#251]
For Stoplight Next 4.2.0, I switched from faker to chance, because it seems not supported as explained in #8. However I couldn't manage to generate data using `chance.js` and could not find any doc about it. Is it supported?

I tried both below:

```js
"x-chance": {
  "integer": {
    "min": 0,
    "max": 100
  }
}
```

```js
"x-chance": "street"
```

**Comment by lottamus** [comment]
Hey @ozum, we currently only support the default keywords from JSON schema faker

You can see all of the supported keywords here: https://github.com/json-schema-faker/json-schema-faker#supported-keywords

You can accomplish the integer example without`x-faker` or `x-chance`.

Here is how I have it working:

```
{
  "type": "object",
  "properties": {
    "int": {
      "type": "integer",
      "minimum": 0,
      "maximum": 100
    }
  },
  "required": [
    "int"
  ]
}
```

**Comment by ozum** [comment]
@lottamus, could you please give an example how to use JSON schema faker for street names in stoplight v4?
