### ISSUE TITLE
Add a body for DELETE methods in try it out

### ISSUE THREAD

**Issue by tbarn** [stoplightio/desktop#257]
Allow DELETE methods to have a body in the try it out feature

Right now the body tab is missing

We allow it in the docs section, talked with @lottamus and we think we should have it for the test requests too

**Comment by geniusdibya** [comment]
Thanks, @tbarn @lottamus for prioritizing this. Looking forward for a quick release, so that we can go live with the DELETE APIs.

**Comment by casserni** [comment]
@geniusdibya sorry for the delay, but this will go out soon!

**Comment by geniusdibya** [comment]
Happy to see this getting released. There are a couple of other issues which I encountered while using Stoplight Next. Will open a new issue for those.
