### ISSUE TITLE
Generated Example format for UUID is incorrect 

### ISSUE THREAD

**Issue by rowa97** [stoplightio/desktop#258]
When generating an example for a UUID, lorem ipsum is generated instead of a UUID example 
<img width="977" alt="screen shot 2018-07-06 at 11 14 04 am" src="https://user-images.githubusercontent.com/29557510/42389334-0620b49c-810e-11e8-9405-4a22bdaf29be.png">

**Comment by lottamus** [comment]
So we don't load all of the faker options, only the ones supported by JSON schema faker.

https://github.com/json-schema-faker/json-schema-faker#supported-keywords

![image](https://user-images.githubusercontent.com/7423098/42720405-1ab7969e-86ec-11e8-8a08-5bfd9ba8fff2.png)

**format — Core formats v4-draft only: date-time, email, hostname, ipv4, ipv6 and uri**

We can optionally include the entire Faker lib which will add a ~335KB chunk file to our platform build. Thoughts @marbemac ?

**Comment by marbemac** [comment]
Let's hold off on the whole faker lib. If it is possible to cherry pick some of those formats then great - or we can probably provide little custom hooks that we write ourselves for the formats we want to support. Not high priority right now though.

**Comment by lottamus** [comment]
Agreed. For now you can accomplish this by adding a pattern property
