### ISSUE TITLE
model schema should allow validation of integer with enum, or null

### ISSUE THREAD

**Issue by MrFidgety** [stoplightio/desktop#26]
Selecting types **integer** and **null** with a enum validation applies the enum validation to both the integer and null, resulting in a failed validation when the value is null.
<img width="302" alt="screen shot 2017-05-24 at 3 41 37 pm" src="https://cloud.githubusercontent.com/assets/13651317/26388422/8722248a-4097-11e7-866c-f17ca521a09c.png">
<img width="862" alt="screen shot 2017-05-24 at 3 42 35 pm" src="https://cloud.githubusercontent.com/assets/13651317/26388439/b196173a-4097-11e7-8b56-ce076a9f0e2d.png">

**Comment by ChrisNLott** [comment]
Fixed and will be released at the end of the week.
