### ISSUE TITLE
Published Hub navigation resets scroll on click

### ISSUE THREAD

**Issue by erik-hansen** [stoplightio/desktop#263]
Only on the published hub pages, when I scroll down a long list of page links in the navigation sidebar and click on one of the page links, the navigation resets back to the top instead of remaining at the same position where I clicked the link.  This makes it very difficult to navigate documentation.

![navigation](https://user-images.githubusercontent.com/6989957/42852925-27ad5bd2-89e8-11e8-98cb-e8a627a3021b.gif)

**Comment by tbarn** [comment]
Hey @erik-hansen! We have released a fix for this. You will need to rebuild your docs. Let us know if you have any issues!
