### ISSUE TITLE
Stoplight URIs in desktop use local hostname

### ISSUE THREAD

**Issue by erik-hansen** [stoplightio/desktop#265]
When using the StopLight desktop app, any time a URI is supposed to point to the public https://next.stoplight.io host, it instead uses a local hostname of stoplight://stoplight.local

Example 1: Creating a Join link
![image](https://user-images.githubusercontent.com/6989957/42915837-0f8aa1ac-8ab7-11e8-8899-f5977ff672b0.png)

Example 2: Adding "Shared/Common" rule to mock server
![image](https://user-images.githubusercontent.com/6989957/42915747-98178090-8ab6-11e8-8b17-298f6a7f248d.png)
...then when you look at the code, the generated URIs resolve to nothing...
![image](https://user-images.githubusercontent.com/6989957/42915803-e410c254-8ab6-11e8-82eb-0790060b7ad7.png)

**Comment by pytlesk4** [comment]
Yes
