### ISSUE TITLE
Can not write comment for embedded model

### ISSUE THREAD

**Issue by usmanovbf** [stoplightio/desktop#270]
Hello! 
As you can see 
![image](https://user-images.githubusercontent.com/18537762/43382409-5906ed54-93e0-11e8-8ed9-67a796cbab90.png), 
![image](https://user-images.githubusercontent.com/18537762/43382423-65c64bc0-93e0-11e8-897d-d7d7121f166e.png)

, I can not write any comment in the embedded model with name IdeableNameable 
![image](https://user-images.githubusercontent.com/18537762/43382438-6fb83558-93e0-11e8-9990-3ce105a84761.png). 
Furthermore, I can not replace a comment in an embedded model by comment in a model that picks up that referenced model

**Comment by usmanovbf** [comment]
The small clarification is that comment and description are same for me

**Comment by tbarn** [comment]
Looks like the same issue as #309, going to close this one since we've opened an internal ticket on that one.
