### ISSUE TITLE
Assertion with 0 is impossible as numeric

### ISSUE THREAD

**Issue by ntiss** [stoplightio/desktop#279]
It's impossible to have an assertion testing the numeric value of `0` : 
![image](https://user-images.githubusercontent.com/29988779/43911744-819fe3ce-9c00-11e8-8796-df65bcdfd8b1.png)

The number `0` is considered as a string in the code, it's surrounded by quotes : 
![image](https://user-images.githubusercontent.com/29988779/43911863-db144d6e-9c00-11e8-9edf-65eb9afeb171.png)

I tried to put `0.0` in the UI without any success. Stoplight always adds quotes in the code.

(And of course, the assertion fails at runtime when it compares `0` to `"0"`)

**Comment by casserni** [comment]
Good find, will go out soon!
