### ISSUE TITLE
Interference between HTTP step and Script step

### ISSUE THREAD

**Issue by samuel-colin** [stoplightio/desktop#28]
Hi,

A problem with a Script step on collection of scenarios.
Here are the steps to replay the bug:
- I create an HTTP Step with "$$. Env.set (" user "," albert ");" on the After script
- I change the HTTP step with Script step
- I add '$$. Env.set ("user", "roger"); on the body
- I run the scenario
- The environment variable 'user' is setting with 'albert' and not 'roger'

I think the After script of HTTP step is already launching.

**Comment by marbemac** [comment]
Ah yes, we should clear the before/after scripts when a step is changed to the "script" type. If you look at the "raw" tab at the bottom of the editor, you should see what's going on here. The after script is still defined in your step. Try deleting that from the JSON in the raw tab. We'll fix the underlying issue when changing to script step type though.

**Comment by ChrisNLott** [comment]
@marbemac @samuel-colin should we straight up delete the before/after scripts or should we add the existing data to the empty script step with some comments separating the `before` and `after`?

**Comment by marbemac** [comment]
@ChrisNLott I like that suggestion - let's go with that. Easy to delete if the user wants to start from scratch. What if they go back to http step type? Should we just clobber it, or just toss the whole thing in the after script? I don't want to do any fancy logic around trying to split the string etc for before/after etc.

**Comment by ChrisNLott** [comment]
Yeah I'd say we'd just take the existing script and put it in either the after script
