### ISSUE TITLE
Add a possiblity to mark a model as deprecated

### ISSUE THREAD

**Issue by usmanovbf** [stoplightio/desktop#286]

**Comment by tbarn** [comment]
Hey! This is a feature right now, but it is a bit hidden: 

<img width="1343" alt="screen shot 2018-12-05 at 11 36 37 am" src="https://user-images.githubusercontent.com/2008034/49532648-a3106e00-f882-11e8-846e-79154da16afe.png">

It looks like this in the UI:

<img width="201" alt="screen shot 2018-12-05 at 11 36 53 am" src="https://user-images.githubusercontent.com/2008034/49532650-a3106e00-f882-11e8-9a6f-608bbe952d8b.png">
