### ISSUE TITLE
Scenario Step Paths Inconsistent

### ISSUE THREAD

**Issue by erik-hansen** [stoplightio/desktop#293]
When I "Create Scenario" from "Swagger/OAS Coverage", the URL for each step encompasses protocol, host, and base path into a single environment variable (e.g. `{$$.env.host}/todos`).

If I create a step manually, click on the URL box (which suggests paths from my OAS def) and select one of the paths, my URL populates with protocol, host, and base path as specified in the OAS def (e.g. `http://todos.stoplight.io/v1/todos`)

Aside from these two methods being inconsistent, neither actually produce a good URL for testing.  What should be automatically populated for URLs is the full path with host always replaced by a variable (e.g. `http://{$$.env.host}/v1/todos`).  Even if host is declared in the OAS def, for testing I want to be able to change the host variable between staging and production.  However, the host environment variable should not be forced to include the protocol and base path components.

**Comment by erik-hansen** [comment]
Update on progress? This is a frequent annoyance...

**Comment by brianmrock** [comment]
Moved this to Jira / ZD.
