### ISSUE TITLE
Left menu gets reset to top when clicking any item which is hidden inside the scroll

### ISSUE THREAD

**Issue by geniusdibya** [stoplightio/desktop#301]
In case someone has a long list of items in the left menu, then a ScrollBar appears.
If you scroll down and click any of the items, then the document reloads and the scrollbar resets to start position (same for menu item too).

This creates a problem because I need to again scroll down to find that item and click on some other.

Here is a screenshot with description. Doc link: https://developers.pepipost.com/api/getstarted/overview
![scroll_pepipost](https://user-images.githubusercontent.com/16018669/44395557-d93a1400-a557-11e8-9ce3-91c92a8523aa.png)

You can replicate this issue in my API docs: https://developers.pepipost.com/sub-accounts/subaccounts
 Goto this link and see what is the scrollbar/side menu position and what content getting displayed in the right pane.

**Comment by tatiana-perry** [comment]
Oops, I opened the same issue. I'll close mines in favor of this one. 
https://github.com/stoplightio/desktop/issues/322

![hub_menu](https://user-images.githubusercontent.com/16635677/45714735-180fb980-bb58-11e8-9023-1909a439b842.gif)

**Comment by tatiana-perry** [comment]
Giving this a bump. Biggest complaint during testing https://devcenter-staging-demo.docs.stoplight.io/

**Comment by tbarn** [comment]
Hey @tatiana-perry, does this look like #263? A fix is in our next release that is about to be released.

**Comment by tbarn** [comment]
@tatiana-perry @geniusdibya could y'all rebuild your docs to see if the latest release fixes this?
