### ISSUE TITLE
Assign environment variables in published documentation through query parameters

### ISSUE THREAD

**Issue by aarunraja** [stoplightio/desktop#308]
Hi,
In the Main page, I have loaded published code in an iframe. The main page has authentication machinimas.  How I can pass auth token from main page to the {$$.env.oauth_access_token} variables in the stoplight published code in Iframe. So the my API call will get success. 
	 
![image](https://user-images.githubusercontent.com/5112852/44795850-4ccbc900-abc9-11e8-884a-c4bf3f9ac12c.png)

**Comment by rossmcdonald** [comment]
Hi @aarunraja, apologies for the delay! This feature is not released yet, but it will work by passing in the variables through query parameters being passed to your iframe. So in your example above, you would want to pass in an `oauth_access_token` query parameter (ie, `?oauth_access_token=abc123`) through to the iframe rendering the document.

We will update this issue once the functionality is available.

**Comment by rossmcdonald** [comment]
Need to update https://github.com/stoplightio/desktop/issues/308 when this functionality is added.

**Comment by lottamus** [comment]
Hey @aarunraja,

This feature has been added and deployed. You will need to republish your Hub for it to work.
