### ISSUE TITLE
Discussion view isn't visible anymore [4.5.1]

### ISSUE THREAD

**Issue by jslowack** [stoplightio/desktop#314]
Hi,

I just tried out the new release 4.5.1 and discovered an issue in the discussion view.
When I drag the detail view to the bottom of the screen, it is gone forever. 
I can't see the discussion anymore, even when i restart the application.

Screenshot in attachment:
![image](https://user-images.githubusercontent.com/797967/45408505-cef9ca00-b66c-11e8-98fa-9660ab63e066.png)

**Comment by casserni** [comment]
@jslowack Ah you are correct! We will have a fix out shortly but in the mean time you can use the developer tools in either your browser or desktop app to clear the application storage and it will come back

**Comment by jslowack** [comment]
Oké, thanks for the workaround!

**Comment by tbarn** [comment]
Hey @jslowack! It looks like this got fixed. Let us know if you are still having issue with it.

**Comment by jslowack** [comment]
Thanks!
