### ISSUE TITLE
Cannot give minLength or maxLength to strings [4.5.2]

### ISSUE THREAD

**Issue by ozum** [stoplightio/desktop#315]
Hi,

Steps to reproduce:

1. Create a model
1. Add an attribute to an object
1. Set it's type `string`
1. Add validation and set `minLength`
1. See error in errors as `INVALID TYPE Expected type integer but found type string`

![image](https://user-images.githubusercontent.com/1497060/45487540-4f045a80-b767-11e8-9773-9abf8b6be405.png)

Kind regards,

**Comment by tbarn** [comment]
Hi! Just wanted to give an update: We're going to add this to the sprint for the next release.

**Comment by juliuszfedyk** [comment]
Hi tbarn! How are we on this?

**Comment by tbarn** [comment]
@juliuszfedyk the sprint started earlier this week and this issue is in progress.

**Comment by lottamus** [comment]
This issue has been fixed in [v4.7.0](https://community.stoplight.io/t/changelog-v4-7-0). Thanks for reporting!
