### ISSUE TITLE
Spotlight API reference does not document authentication

### ISSUE THREAD

**Issue by mduesterhoeft** [stoplightio/desktop#329]
I would like to work with your publish API documented here - https://docs.stoplight.io/api-reference/documentation

The API reference does not state how to do authentication. I have generated an access token but it is unclear how to pass it to the API.

**Comment by tbarn** [comment]
Hey @mduesterhoeft! We had a small bug related to this that needed to be fixed, but it won't go out until the next release which should hopefully be by tomorrow. The docs will be updated then too. I'll share it here too once it is live.

**Comment by tbarn** [comment]
The authentication section is a bit more helpful now: https://docs.stoplight.io/api-reference/documentation#authentication

I'm going to go ahead and close this. If you have any auth issues, let me know.

**Comment by mduesterhoeft** [comment]
@tbarn Thank you - this is much better now!
