### ISSUE TITLE
Clarify difference between Stoplight and Stoplight Classic

### ISSUE THREAD

**Issue by leoarnold** [stoplightio/desktop#331]
I cannot log in at https://next.stoplight.io, but on https://app.stoplight.io I can. What's the background of this?

![screenshot_20181011_113602](https://user-images.githubusercontent.com/4201235/46795315-22ce0080-cd4a-11e8-8f56-e3cbe128eef3.png)

**Comment by tbarn** [comment]
Hi @leoarnold! Stoplight Next is our latest version. Both Classic and Next are being supported now. Eventually, we will encourage and help users migrate to Next, but for now, you don't need to.
