### ISSUE TITLE
Custom CSS loading out of order since latest release

### ISSUE THREAD

**Issue by stevenbennitt** [stoplightio/desktop#333]
Since the release yesterday afternoon, the custom.css styles are now being overridden by  main.css and styles.css styles. 

It appears to be requesting, receiving and processing them in a different order now 

My only workaround at the moment would be to add !important tags to all my custom css which I'd really not like to do.

**Comment by lottamus** [comment]
This issue has been fixed and deployed. You will need to republish your docs for the changes to take effect.
