### ISSUE TITLE
UI Crashes : "Darn! Something went wrong"

### ISSUE THREAD

**Issue by ntiss** [stoplightio/desktop#335]
The UI often crashes when modeling and switching between panes, or anything else.
Here is a simple way to reproduce in the "Servers" section : 
 - first, display an "API",
 - then, go on "RULES"
 - finally go back on the API... and crash.

See this GIF :
![bug_crashui_in_mock](https://user-images.githubusercontent.com/29988779/47303452-3455b900-d624-11e8-9c75-f9240d98bdb1.gif)

**Comment by tbarn** [comment]
Hey @ntiss! We should have a fix for this soon.

**Comment by ntiss** [comment]
Hi Taylor,

Thanks, I hope that it will fix all issues like this.
I found another easy way to reproduce in the "Testing" section : 

![bug_crashui_in_scenario](https://user-images.githubusercontent.com/29988779/47423835-5d8e5a80-d786-11e8-958b-63057ebba8d9.gif)

- first, open the "Contract Test Settings" bloc (important)
- then, display anything else.
- go back to Swagget/OAS Coverage... and crash

(same traces in the console)

**Comment by rossmcdonald** [comment]
@ntiss The fix for this issue is now in production. Let us know if you continue to see these errors.

**Comment by ntiss** [comment]
Hi, please reopen this issue.
Here is a new way to reproduce : 
 - open a project
 - view a scenario
 - open the "Trigger This Collection"... and crash

In a GIF : 
![bug_crashui_in_triggerthisscenario](https://user-images.githubusercontent.com/29988779/47738050-9345ae80-dc72-11e8-8c55-ebaa13be8578.gif)

This issue is now blocking because we can't read the commandline elsewhere.

**Comment by rossmcdonald** [comment]
@ntiss Thanks for letting us know. Looking into this now.

**Comment by ntiss** [comment]
Fixed on hosted version.
