### ISSUE TITLE
Mocking fails if the file contains a space

### ISSUE THREAD

**Issue by ntiss** [stoplightio/desktop#336]
The Prism Server fails if the server filename contains a space : 
![image](https://user-images.githubusercontent.com/29988779/47304204-3b7dc680-d626-11e8-99d5-d13e709fbb51.png)

Solutions : 
 - either prevent the user from creating a such file right from the beginning in the creation screen
 - or url-encode the filename in the Prism url (with %20)

**Comment by tbarn** [comment]
Hey @ntiss! I believe @pytlesk4 is looking into this right now.

**Comment by tbarn** [comment]
He'll get a build out later today fixing it!
