### ISSUE TITLE
File name is too long in Servers (Mock)

### ISSUE THREAD

**Issue by ntiss** [stoplightio/desktop#337]
It's possible to create a prism serveur with this name "aVeryVeryVeryVeryLongFilename" without any warning in the creation screen. 

The "Create" button works but there is an error message in the UI right after : 
![image](https://user-images.githubusercontent.com/29988779/47304532-353c1a00-d627-11e8-8737-5a0a97a3c9e5.png)

(Of course, it's not possible to rename the file)

**Comment by lottamus** [comment]
Hey @ntiss ,

We've updated the UI to show an error. A work around to renaming the file is to open the raw view and copy the file contents then create a new file.

![image](https://user-images.githubusercontent.com/7423098/48249982-5a1fe380-e3c2-11e8-99e5-0b1e993d7ba1.png)
