### ISSUE TITLE
Request using the desktop client fails

### ISSUE THREAD

**Issue by Julioocz** [stoplightio/desktop#339]
The prism server after using the app for a few seconds or after making a request.

![image](https://user-images.githubusercontent.com/21016151/47580402-6ad94f80-d914-11e8-9af7-8e524f8cbd52.png)

[stoplight.local-1540572104394.log](https://github.com/stoplightio/desktop/files/2520057/stoplight.local-1540572104394.log)

**Comment by tbarn** [comment]
Hi @Julioocz! We'd love to check this out on your project specifically. Could you send us an email to support@stoplight.io with the name of the organization/project? Also, what version of the desktop app are you using?

**Comment by tbarn** [comment]
I'm going to go ahead and closet this issue since we are talking about it via support specific to your specification. We'll get it figured out there!
