### ISSUE TITLE
Enhance resource editor in CRUD builder

### ISSUE THREAD

**Issue by ntiss** [stoplightio/desktop#34]
Users don't always know how to design a JSON resource. So, they aren't able to use the CRUD Builder.
Please implement the WYSIWYG resource editor in the CRUD Builder of Scenario. (Just like in the legacy desktop app).
![capture_stoplight-legacy](https://user-images.githubusercontent.com/29988779/30210190-e9d65c1a-949b-11e7-9f95-3e6c27777644.png)

Other idea : add a feature to quickly create all CRUD operations directly from an existing model.

**Comment by marbemac** [comment]
Great suggestions! I chatted with the team, and we'd like to get both in. I've split this out into two issues that you can subscribe to here:

https://github.com/stoplightio/desktop/issues/36
https://github.com/stoplightio/desktop/issues/37

Closing this one out.

**Comment by ntiss** [comment]
Great, thank you.
