### ISSUE TITLE
Testing : Linked steps with old exporter URL doesn't work

### ISSUE THREAD

**Issue by ntiss** [stoplightio/desktop#342]
It fails when running a step linked to an external scenario with the old exporter url : 
![image](https://user-images.githubusercontent.com/29988779/47668078-d555ee00-dba7-11e8-8382-ed788d9b22ef.png)

Is there a workaround? (except moving to the new url format because of #341 )
Do you plan to update all the urls in the scenarios of the customer ?

**Comment by tbarn** [comment]
@ntiss all good now?

**Comment by ntiss** [comment]
Hi Taylor,
The issue still occurs when using the old exporter URL. Have you tried to fix something ?

**Comment by tbarn** [comment]
@ntiss I'm going to reach out to get this fixed in your specification specifically and close for now.
