### ISSUE TITLE
Allow for json objects to be copy/paste

### ISSUE THREAD

**Issue by tatiana-perry** [stoplightio/desktop#345]
Currently, the site does now allow for JSON schemas to be copy/pasted or even selected. This persists across the visual editor and on the API Reference pages. 

Examples:
https://developer.bigcommerce.com/api-docs/catalog/products/products-overview#products-overview_object-properties
https://developer.bigcommerce.com/api-reference/catalog/catalog-api/catalog/getvariants

It would be great if the text within the schema in the user docs could be copy/pasted. 

![2018-11-21 11-21-37 2018-11-21 11_22_36](https://user-images.githubusercontent.com/16635677/48857955-cc5bd500-ed7f-11e8-8e55-7516e1c492a5.gif)

**Comment by tbarn** [comment]
Until this is fixed, here's a workaround that may help you: https://community.stoplight.io/t/make-api-reference-content-pulled-from-swagger-copyable/186/3

**Comment by tatiana-perry** [comment]
That worked! Thank you!
