### ISSUE TITLE
Webpage with javascript show in meta description

### ISSUE THREAD

**Issue by tatiana-perry** [stoplightio/desktop#346]
https://developer.bigcommerce.com/changelog
When sharing a link to a page that is just javascript it shows the javascript used to create the page in the meta description. 

Workaround for anyone else having this issue:
Create html that is 132 characters.Tags, line breaks (`</br`>) and spaces do not count. 

<img width="589" alt="screen shot 2018-11-27 at 3 18 35 pm" src="https://user-images.githubusercontent.com/16635677/49112189-b9517500-f257-11e8-8837-bdc849575ce5.png">

**Comment by tbarn** [comment]
Nice catch. Just before I go try it, did you try putting in a meta description into a `<head>` tag in the HTML file?

**Comment by tbarn** [comment]
And if that doesn't work, what to do think about that as a solution? Allows you to set your own meta tags on HTML pages.

**Comment by tatiana-perry** [comment]
Setting a head and meta tag, still returns the same results.  I have tried to set it up like a webpage with a head, body element with the same results. 
<img width="1044" alt="screen shot 2018-11-27 at 4 33 08 pm" src="https://user-images.githubusercontent.com/16635677/49116096-341f8d80-f262-11e8-9f00-b5f7619d00a6.png">

**Comment by tbarn** [comment]
Good to know. I've opened up something internally to get this fixed up.

**Comment by tbarn** [comment]
Hey @tatiana-perry, we believe this issue is now fixed. I'm going to close for now unless you have a case where it is still happening.
