### ISSUE TITLE
Weird  behaviour with the private variables editor

### ISSUE THREAD

**Issue by ntiss** [stoplightio/desktop#350]
The private variables are only visible and editable after clicking twice on the "Resolved" toggle button.
It's the deactivation of "Resolved" that makes the JSON bloc appear in a correct manner. 

See this gif : 
![issue_privatevarseditor](https://user-images.githubusercontent.com/29988779/49675380-b2a3d880-fa75-11e8-96c7-f6f87f89ef1a.gif)

Reproduced on Chrome (71.0.3578.80) and also in the desktop app.
Perhaps related to the issue #349.

**Comment by mta59066** [comment]
I have a similar problem where I don't see the ".stoplight" under CONFIG section on the lower left corner, and when I open Environments window, I don't see "Default", "Staging" and "Production".

**Comment by rossmcdonald** [comment]
@mta59066 Can you give us more information about your environment (browser, desktop app, etc)? And does this issue happen consistently?

We haven't had any other reports of the `.stoplight` file missing or the Environments window not displaying the appropriate environments.

**Comment by tbarn** [comment]
This was fixed in v4.8.0, which was just released. You can see the changelot at: https://community.stoplight.io/t/changelog-v4-8-0/
