### ISSUE TITLE
Hubs --> Links with query parameters are being escaped in markdown

### ISSUE THREAD

**Issue by lottamus** [stoplightio/desktop#353]
**Reproduce**
1. Create a Hub or Markdown file
2. Create a markdown link with query params such as `[click here](https://example.com?foo=1&bar=2)`
3. Notice the link resolves to https://example.com/?foo=1&amp%3Bbar=2 instead of https://example.com/?foo=1&bar=2

**Comment by brianmrock** [comment]
This fix is scheduled for the next release near the end of January

**Comment by tbarn** [comment]
Fixed in v4.8.0
