### ISSUE TITLE
All API pages are broken! 

### ISSUE THREAD

**Issue by erikkai** [stoplightio/desktop#355]
I have pages where I call out an individual API and show a piece of it as reference material. Something happened in the past two weeks where every single API reference is broken and it will not correctly display the content of the JSON file. There are multiple parameters and it will show 1 parameter incorrectly formatted on many of the pages. 

I had to roll back 2 weeks to get things working but I would like to find out why this is happening. I thought it was the lint settings but that doesn't seem to work - I turned off every single setting just to be sure and no luck.

**Comment by lottamus** [comment]
Hey @erikkai ,

That's not good! Is this only happening in the Stoplight Platform, only in your published Hub, or in both places?

>  every single API reference is broken and it will not correctly display the content of the JSON file.

Are these references to a full API spec or are they references to a single operation inside the API spec?

**Comment by erikkai** [comment]
They are references to a piece of an API inside a spec.

This has always worked and very suddenly doesn’t.
