### ISSUE TITLE
Export swagger Integer values treated as string 

### ISSUE THREAD

**Issue by aarunraja** [stoplightio/desktop#357]
When i try to export the swagger from stoplight and try to import to API Gateway (Azure API management) i am getting following error .
Parsing error(s): Invalid type. Expected Integer but got String. Path definitions.Address.allOf[0].properties.address1.maxLength'

Parsing error(s): Invalid type. Expected Integer but got String. Path 'definitions['NotificationSchedule Create'].properties.scheduleName.maxLength'

Solution:
i have removed the double quotes in the numeric value.   
"maxLength": "100"  to "maxLength": 100

**Comment by tbarn** [comment]
Hey @aarunraja, are you using the web or desktop app? It should be now fixed in the web app, and we will get it out in a release for the desktop app soon.

**Comment by tbarn** [comment]
I'm going to go ahead and close this since it looks like it is fixed. We can reopen it if you are still seeing it in the web application.
