### ISSUE TITLE
Remote ref are not resolved

### ISSUE THREAD

**Issue by remik** [stoplightio/desktop#358]
If I try to resolve "all" or "remote" it is not resolving remote ref.

Project is private. 
The example url: https://next-api.stoplight.io/files.export?projectId=8848&branch=version%2F2.17&path=public%20apis.oas2.yml&deref=all

The example export part:
```
"paths": {
        "/v2/risk/order/processors": {
            "post": {
                "operationId": "POST_v2-risk-order-processors",
                "summary": "Check Processor Order",
                "tags": [
                    "Check"
                ],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "/models.oas2.yml#/definitions/schema-risk-order-request-processor"
                        }
                    }
                ],
```

**Comment by tbarn** [comment]
Hey @remik, I believe we have a fix going out for this soon. Let me check in on the internal issue.

**Comment by tbarn** [comment]
Just confirmed, the fix is in testing right now to fix that `deref=all` isn't dereferencing external references for private projects.

**Comment by remik** [comment]
Great. Wait for the release :)

**Comment by pytlesk4** [comment]
@remik Release went out tonight, let us know if the issue is resolved.

**Comment by remik** [comment]
All good now. Thanks!
