### ISSUE TITLE
Build & Publish - cryptic Docker error message

### ISSUE THREAD

**Issue by denver-HJS** [stoplightio/desktop#359]
When I try to build and publish my documentation portal I'm receiving an error, but there doesn't seem to be any feedback whether or not it's something I can resolve on my own.

The attached image shows the behavior.

![stoplight-build-error](https://user-images.githubusercontent.com/1916018/51418662-bbd69980-1b39-11e9-919a-231c9497ccd5.jpg)

**Comment by rossmcdonald** [comment]
@denver-HJS It looks like one of our servers was misconfigured, which was causing doc builds to intermittently fail. The issue has been corrected now, but let us know if you run into any further issues.
