### ISSUE TITLE
Response schema rendering suddenly broken

### ISSUE THREAD

**Issue by distinctgrey** [stoplightio/desktop#360]
Since very recently response schemas do not show anymore, both in Read view (web version) and published docs. In the desktop app (4.7.0, macOS) it's still working.

**macOS app v4.7.0:**
![screenshot 2019-01-21 at 12 03 14](https://user-images.githubusercontent.com/1928790/51470719-009a4480-1d75-11e9-9dc6-cee6959122b5.png)

**web app / published docs:**
![screenshot 2019-01-21 at 12 03 27](https://user-images.githubusercontent.com/1928790/51470750-160f6e80-1d75-11e9-8a14-c2e0a05ab893.png)

**Comment by rossmcdonald** [comment]
@distinctgrey Does your response schema use a combination type (`allOf`, for example)?

**Comment by distinctgrey** [comment]
That's correct @rossmcdonald.
