### ISSUE TITLE
We lost changes made yesterday

### ISSUE THREAD

**Issue by horatiucherebetiu** [stoplightio/desktop#365]
Hello,

We lost changes made yesterday on https://next.stoplight.io/sdl-1.
Can you help?

Best regards,
Horatiu Cherebetiu

**Comment by tbarn** [comment]
Hey @horatiucherebetiu! 

In order to best help you with issues like this, it would be best to email into support@stoplight.io with the specific project you are seeing issues with. It will also help to have some more information on what you feel like you lost. Thanks!
