### ISSUE TITLE
Bug report: cannot save lint changes

### ISSUE THREAD

**Issue by distinctgrey** [stoplightio/desktop#366]
Platform: both web app & macOS app.
Version: 4.8.0 (latest)

Steps to reproduce:
1/ Navigate to "lint" config file in a project.
2/ Toggle a rule

Expected behavior:
"Save" button becomes enabled.

Actual behavior:
"Save" button stays disabled. After reload of the screen, the changed rule is not persisted.

**Comment by tbarn** [comment]
Sorry about not updating here sooner. We have a fix for this now. Will follow up here: https://community.stoplight.io/t/bug-report-cannot-save-lint-rule-changes/494/2

**Comment by tbarn** [comment]
I will continue on this in the forum.
