### ISSUE TITLE
Tags when importing swagger file

### ISSUE THREAD

**Issue by ehosanski** [stoplightio/desktop#39]
When importing a swagger specification, tags are visible when on individual endpoint but cannot be seen in the tag section  

<img width="1128" alt="capture d ecran 2017-09-21 a 09 13 50" src="https://user-images.githubusercontent.com/25955608/30683316-42db3266-9ead-11e7-8fd9-071283dd581e.png">
<img width="1125" alt="capture d ecran 2017-09-21 a 09 14 03" src="https://user-images.githubusercontent.com/25955608/30683317-42dd1450-9ead-11e7-83fb-fb11156f7626.png">

**Comment by marbemac** [comment]
Hi @ehosanski - we actually don't touch the imported swagger file at all. Are those root level tags present in the original, uploaded Swagger file? If not, that's whey they are not showing up after importing :).

**Comment by ehosanski** [comment]
Hi @marbemac - that's it, the tag part of the swagger file wasn't correctly formatted... Thanks for your quick response 😃
