### ISSUE TITLE
String type does not support open format

### ISSUE THREAD

**Issue by svallory** [stoplightio/desktop#43]
According to swagger documentation

"format is an open value, so you can use any formats, even not those defined by the OpenAPI Specification, such as: email, uuid, uri..." - [swagger docs](https://swagger.io/docs/specification/data-models/data-types/)

I think a couple formats should be in the options, notably `uuid` which is present in stoplight.io. But any value should be accepted.

**Comment by marbemac** [comment]
Hi @svallory, for now you could pop into the raw schema / spec and add any format you want to the property in question. Will chat with the team about a free-form format input.

**Comment by svallory** [comment]
@marbemac I know that, but scenarios not showing the value in the edit form is really confusing for other devs (the ones that did not set it manually).

You could at least show the value currently in the spec

**Comment by marbemac** [comment]
Agreed, will fix! Raw schema is just a temp solution to get it in there now.

**Comment by marbemac** [comment]
Done @ next.stoplight.io. Will be included in our deploy tomorrow. Will close when its live.
