### ISSUE TITLE
Can't delete path in try it out url

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/desktop#46]

**Comment by marbemac** [comment]
When you have a moment, add a bit more info - don't really know what this means.

**Comment by pytlesk4** [comment]
![typingissue](https://user-images.githubusercontent.com/2294309/31161700-76045474-a89e-11e7-9980-a88c5986e589.gif)

**Comment by marbemac** [comment]
This is tricky, because you are basically deleting only part of that first url segment, which leads to an invalid URL, which we cannot parse.

google.com/foo/bar
google.como/bar

Feels like an edge case that is easy to work around, closing for now.
