### ISSUE TITLE
ENUM Validations Not Displaying in Spec Editor

### ISSUE THREAD

**Issue by dave-scott-invenco** [stoplightio/desktop#48]
Hi,

Seems like there is a bit of a one-way bug with entering ENUM values into a spec model.

I can successfully add ENUM validations to a model property via the SPEC editor, and this successfully updates the local spec file per below:

![screen shot 2017-10-04 at 1 44 28 pm](https://user-images.githubusercontent.com/21297907/31157999-7290d0ee-a90a-11e7-96c8-59125be88a33.png)

However, when I reload the spec again via the desktop app via 3.4.1 (Mac), the editor or viewer does not seem to read or display the enum or format validation data from the swagger.json file per the below screenshot.

![screen shot 2017-10-04 at 1 44 38 pm](https://user-images.githubusercontent.com/21297907/31158038-a5a6a968-a90a-11e7-9e4b-e30383103d94.png)

Thanks, 
Dave

**Comment by ChrisNLott** [comment]
Can't reproduce

**Comment by dave-scott-invenco** [comment]
Hi Chris,

Seems to have resolved over the course of update from Scenarios to Stoplight Next 3.5.

Ok to close this now, but thanks for checking.

Dave
