### ISSUE TITLE
Copy text in input fields trims characters - gif included

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/desktop#49]
![brokenCopy.gif](https://codetreeusercontent.s3.amazonaws.com/uploads/9a4856ae-6f1a-4656-8429-ce776b245160/brokenCopy.gif)

Notice the missing quote at the end of the pasted string.

**Comment by marbemac** [comment]
1) that is not valid json.
2) this would be deep in codemirror, which we don't have time to dive into right now.
3) feels like an edge case :)
