### ISSUE TITLE
Authorization header is missing from step added from Coverage when specified in securityDefinitions

### ISSUE THREAD

**Issue by mccataldo** [stoplightio/desktop#5]
When adding a step from Coverage, the Authorization header is missing when specified in `securityDefinitions` as follows: 

```
{
  "Authorization": {
    "name": "Authorization",
    "type": "apiKey",
    "in": "header"
  }
}
```

**Comment by ChrisNLott** [comment]
Hey @mccataldo, how are you adding it to the operation? It looks for a "security" array on the operation.

```
  "security": [
    {
      "Authorization": []
    }
```

**Comment by marbemac** [comment]
@mccataldo are you able to confirm if this is still an issue?

**Comment by ChrisNLott** [comment]
Confirmed this is working
