### ISSUE TITLE
Code block not contained, it is out of control, and it is too late. It has already run off the edge.

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/desktop#50]
https://scenarios.stoplight.io/stoplight/hubs/prism/hub/runtime/reference

**Comment by marbemac** [comment]
Looks like that hub is no longer a thing - can you update the link when you have a chance?

**Comment by pytlesk4** [comment]
https://scenarios.stoplight.io/bear/hubs/prism-docs/hub/runtime/reference

**Comment by ChrisNLott** [comment]
Should be fixed with 0e1edd946b88958d91a2bfd7f867986a583ae237
