### ISSUE TITLE
Spec statuses missing 422: Unprocessable Entity

### ISSUE THREAD

**Issue by knightstick** [stoplightio/desktop#6]
![image](https://cloud.githubusercontent.com/assets/5941208/23734992/f714e964-04d6-11e7-9b07-6437b1a2007d.png)

I am using Stoplight to create a swagger spec, and then linking it to Scenarios in order to test my API. However, when I select 422 Unprocessable Entity as the response status (as is convention for Rails validation errors), the status does not appear in Scenarios.

Further to this, it is then not possible to select this status in the Scenario itself, making it impossible to test this respons.

**Comment by marbemac** [comment]
Hi there, great catch. Will add 422 for the next release (tomorrow)!

**Comment by knightstick** [comment]
@marbemac Perfect! Thanks for the quick response!

**Comment by marbemac** [comment]
Released!

**Comment by knightstick** [comment]
@marbemac Can confirm this is working as expected! Thanks again
