### ISSUE TITLE
Not generating prism conduct commmand properly

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/desktop#63]
![prismconduct.png](https://codetreeusercontent.s3.amazonaws.com/uploads/757c867d-62be-40b1-9f98-2a20e8f52fb8/prismconduct.png)

**Comment by rossmcdonald** [comment]
I've found some other examples of this issue:

![screenshot-2017-11-27 helpers scenarios yml prism stoplight](https://user-images.githubusercontent.com/4060903/33279842-aac6ccd6-d365-11e7-8e2c-a40425c548b8.png)
