### ISSUE TITLE
referencing utitlity functions get overwritten

### ISSUE THREAD

**Issue by russmilburn** [stoplightio/desktop#64]
I have two reference scripts in two different scenarios

Scenario A
	ref step A
	
Scenario B
	ref step B
	
reference step A has the following ref
	"$ref": "https://exporter.stoplight.io/3057/master/functional.scenarios.yml#/utilities/aaaaa"

reference step B has the following ref	
	"$ref": "https://exporter.stoplight.io/3057/master/functional.scenarios.yml#/utilities/bbbb"

When I click on ref step A in visual mode and then click on ref step B reference B will be overwritten

and both ref step A and B will be referencing the same reference script 
	"$ref": "https://exporter.stoplight.io/3057/master/functional.scenarios.yml#/utilities/aaaa"

I am using the web app in mac OSX 10.12.6

**Comment by marbemac** [comment]
Thanks for the report! Just got this fixed, will make it into our next deploy. Will close this when its live

**Comment by marbemac** [comment]
Deployed, please re-open if you notice again!
