### ISSUE TITLE
pathParam not supported in HTTP Request Maker

### ISSUE THREAD

**Issue by ntiss** [stoplightio/desktop#67]
The curly braces aren't detected.

![issue_pathparam](https://user-images.githubusercontent.com/29988779/32679713-b10c9e0a-c667-11e7-9f86-d6b0d204b838.jpg)

**Comment by marbemac** [comment]
This should be fixed, please let us know if otherwise!

**Comment by ntiss** [comment]
Yes, I confirm that it's fixed. Thank you.
