### ISSUE TITLE
problems due to API basePath in the HTTP Request Maker

### ISSUE THREAD

**Issue by ntiss** [stoplightio/desktop#68]
![issue_basepath](https://user-images.githubusercontent.com/29988779/32680658-f02a4b88-c66b-11e7-8984-6f7c3e16d1f4.gif)

**Comment by ntiss** [comment]
Any news for this issue ?
Things have change a bit since there is no more {$$.en.host} variable but it is still bugged.
Here a new GIF :
![issue_basepath2](https://user-images.githubusercontent.com/29988779/33629486-7e121e98-da04-11e7-824c-2960b7690128.gif)

This bug is very annoying for the users when testing a lot of requests. They have to manually change the path each time.

**Comment by marbemac** [comment]
@ntiss This is all fixed up for our deploy (happening this evening or tomorrow). I'll close this out once its live.

**Comment by ntiss** [comment]
Hello Marc,
I just figured out that this bug has also an impact on scenario execution.
If the basePath doesn't match exactly, the OAS coverage percentage stays at 0%.
(Perhaps to threat in an other issue)

**Comment by marbemac** [comment]
@ntiss In order for coverage to work, the final resolved http request (after all variable replacement etc) that is sent to your servers must match something in your OAS specification. 

Prism looks up a request in your OAS file like so:

IF incoming HTTP request is GET `/v1/users/1`

THEN prism will:
- prepend your OAS basePath to all paths in the OAS file.
- try to find a GET operation for the /v1/users/1 path

So if your oas looks like this:

```
basePath: /v1
paths:
  /users:
    ...operations
  /users/{id}
    ...operations
```

Prism turns it into this:

```
paths:
  /v1/users:
    ...operations
  /v1/users/{id}
    ...operations
```

Then tries to lookup /v1/users/1 in that list of paths (which would, in this case, match /v1/users/{id}).

Does that make sense? If there is still an bug here on our end, lets open up an issue and chat about it!

**Comment by ntiss** [comment]
Yes, that makes sense. I'll let you know when this issue is closed, and talk by chat if needed.

**Comment by marbemac** [comment]
Should be all set, deployed last night - please let us know if otherwise!
