### ISSUE TITLE
UI bug when moving steps in a scenario with drag'n drop

### ISSUE THREAD

**Issue by ntiss** [stoplightio/desktop#72]
It's only a display bug. The steps aren't really duplicated. See GIF below.
Temporary workaround :  use the "</> Code" pane to move JSON blocks.

![issue_movestep](https://user-images.githubusercontent.com/29988779/32809808-a2a9e8e8-c998-11e7-9a1e-c7ed23fb1644.gif)

**Comment by marbemac** [comment]
As always, thanks for the useful gif! Will fix up in the next couple of days.

**Comment by marbemac** [comment]
This was fixed in the release deployed tonight.
