### ISSUE TITLE
Can't create project because route taken, when it isn't

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/desktop#75]
https://next.stoplight.io/stoplight/prism

The above project doesn't exist.

![routetaken.png](https://codetreeusercontent.s3.amazonaws.com/uploads/c7b37690-5dda-44b5-912e-ffc45025182a/routetaken.png)

**Comment by marbemac** [comment]
Teams and projects share the same namespace within an org - there is a team called "prism". Remove it and you should be all good.
