### ISSUE TITLE
Referenced header parameters not showing in UI

### ISSUE THREAD

**Issue by johnmckinzie** [stoplightio/desktop#79]
In my `common.oas2` file, I have defined header parameters that I would like to reference in several endpoints which are in a separate API file. I am able add them in my API file, but after they have been added, they do not show up in the UI. However, I am to see them in the **Code** view.
![UI](https://user-images.githubusercontent.com/2511456/33039236-41c80444-ce05-11e7-8d66-c66af185759d.png)
![Code](https://user-images.githubusercontent.com/2511456/33039252-4c096614-ce05-11e7-9e97-9198ab9c3a17.png)

**Comment by marbemac** [comment]
Fixed in this evening's release. Please let us know if you run into it again!

**Comment by johnmckinzie** [comment]
The fix has appeared to introduce a new bug. When I try and added a **Headers** parameter by reference, it shows up in the **Query Parameters** section instead.

**Comment by marbemac** [comment]
Hmm, could you do a quick double check on the shared parameter to make sure that it is marked as a header, and not a query string? (as defined in your common specification shared parameters section).
