### ISSUE TITLE
Missing files in last release (?)

### ISSUE THREAD

**Issue by ntiss** [stoplightio/desktop#81]
Some files seems missing in the last release 3.5.3.
The screen "Hosts configuration" does'nt work anymore : the page stays blue.

In the Developper Tools, there is an error on index.html :
![image](https://user-images.githubusercontent.com/29988779/33081590-00a949a6-cedb-11e7-8297-fc9af984c6bb.png)

(And the file is indeed missing in /opt/resources/app/build

**Comment by marbemac** [comment]
Should be fixed in 3.5.4, please let us know if otherwise!
