### ISSUE TITLE
Use the model title in the instead of model key in the list

### ISSUE THREAD

**Issue by johnmckinzie** [stoplightio/desktop#82]
It appears that the model list in the middle pane is using the model key and not the model title. It would be nice if it use the human-readable title.
![model list](https://user-images.githubusercontent.com/2511456/33093292-9df91148-ceca-11e7-8a1a-083f755d34e0.png)

**Comment by marbemac** [comment]
Agreed, and a simple enhancement.

**Comment by marbemac** [comment]
Deployed in tonight's update.
