### ISSUE TITLE
Support dependencies in the JSON Schema Editor

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/desktop#83]
[JSON Schema Dependencies](https://stackoverflow.com/questions/38717933/jsonschema-attribute-conditionally-required) let you conditionally require a property.

**Comment by marbemac** [comment]
Interesting - will require a bit of re-work in the JSE. Does gojsonschema support this?

**Comment by marbemac** [comment]
Def won't be able to fit into this sprint - this will be non-trivial.
