### ISSUE TITLE
Preserve description when switching from primitive type to a combiner type

### ISSUE THREAD

**Issue by jflyerme** [stoplightio/desktop#84]
In the editor when switching an existing property from primitive to combiner the description is not preserved.

<img width="1083" alt="screen shot 2017-11-21 at 3 04 51 pm" src="https://user-images.githubusercontent.com/19435702/33099651-ccf5ed1e-cece-11e7-9b42-9e6a3043e5b5.png">

**Comment by marbemac** [comment]
Deployed in tonight's update.
