### ISSUE TITLE
Circular Scenario Refs aren't displaying results correctly

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/desktop#95]
- The issue has to do with input getting turned into a string "[Circular ~.phase.scenarioId]"

**Comment by marbemac** [comment]
Can you add a way to reproduce this?

**Comment by pytlesk4** [comment]
Run this scenario: https://next.stoplight.io/stoplight/prism/blob/master/features.test.scenarios.yml?edit=%23%2Fscenarios%2Fhjg

**Comment by marbemac** [comment]
@pytlesk4 looks OK to me in dev - am I looking in the wrong place? Need more info.

<img width="1365" alt="screen shot 2017-12-12 at 11 47 29 pm" src="https://user-images.githubusercontent.com/847542/33923450-d8184894-df96-11e7-84c0-0c4cbaa71a47.png">

**Comment by pytlesk4** [comment]
I fixed it in prism, all good.
