### ISSUE TITLE
Deleting a shared response doesn't work

### ISSUE THREAD

**Issue by ntiss** [stoplightio/desktop#98]
In modeling, when deleting a shared response, there is the confirm popup but no effect if I confirm the deletion.
The response is still present in the swagger. There is no trace in the console.
I have to delete the response in the "</>Code" pane.

**Comment by marbemac** [comment]
@casserni let's fix this up today please, after the ref builder thing (or if ref builder will take longer than a few hours, then pause and hop on this).

**Comment by casserni** [comment]
I am having difficulty reproducing this issue. Would you be able to share a specific list of steps or spec that I can follow to try and recreate this?

**Comment by ntiss** [comment]
Yes, of course.
Here it is :
![issue_deletesharedresponse](https://user-images.githubusercontent.com/29988779/33628544-5900530c-da01-11e7-8515-c2e921cbef7d.gif)

**Comment by marbemac** [comment]
Deployed last night.
