### ISSUE TITLE
[RefBuilder] Switching from "this file" to any other target closes popup

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/desktop#99]
![thisfileissue.gif](https://codetreeusercontent.s3.amazonaws.com/uploads/98ac4cfe-349c-4b38-bbed-bddcac43f134/thisfileissue.gif)

**Comment by marbemac** [comment]
FF only or is this also confirmed in Chrome (in develop environment)?

**Comment by pytlesk4** [comment]
Only happens in Firefox for me, specifically Firefox Developer Addition

**Comment by marbemac** [comment]
Does it occur in FF regular edition? If this is isolated to developer addition, I think we close it.

**Comment by pytlesk4** [comment]
Happens in regular
